/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.7.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QToolButton>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QAction *actionOpen;
    QAction *actionSave;
    QAction *actionExit;
    QAction *actionAbout;
    QAction *actionFromGameCus;
    QAction *actionFromExternalCus;
    QAction *actionImportSkillDir;
    QAction *actionFromGameIdb;
    QAction *actionFromGamePup;
    QAction *actionFromExternalPup;
    QAction *actionFromPupSkillUsage;
    QAction *actionFromGameAur;
    QAction *actionFromExternalAur;
    QAction *actionFromAuraSkillUsage;
    QAction *actionFromAuraCharUsage;
    QAction *actionFromAuraPatchSkillUsage;
    QAction *actionFromHumBcs;
    QAction *actionFromHufBcs;
    QAction *actionFromBcsFile;
    QAction *actionFromHumBcsEyes;
    QAction *actionFromHufBcsEyes;
    QAction *actionFromNmcBcsEyes;
    QAction *actionFromFriBcsEyes;
    QAction *actionFromMamBcsEyes;
    QAction *actionFromMafBcsEyes;
    QAction *actionFromBcsFileEyes;
    QAction *actionFromHumBcsMore;
    QAction *actionFromHufBcsMore;
    QAction *actionFromNmcBcsMore;
    QAction *actionFromFriBcsMore;
    QAction *actionFromMamBcsMore;
    QAction *actionFromMafBcsMore;
    QAction *actionFromBcsFileMore;
    QAction *actionFromCmnBpe;
    QAction *actionFromCmnBpeBO;
    QWidget *centralWidget;
    QTabWidget *tabWidget;
    QWidget *modInfoTab;
    QLineEdit *modNameEdit;
    QLabel *label_2;
    QPushButton *guidButton;
    QLabel *label;
    QLineEdit *modVersionEdit;
    QLineEdit *modAuthorEdit;
    QLabel *label_5;
    QLabel *label_4;
    QLineEdit *modGuidEdit;
    QComboBox *skillNameLangComboBox;
    QLabel *label_3;
    QLineEdit *skillNameEdit;
    QPushButton *skillNameCopyButton;
    QLabel *label_6;
    QComboBox *skillTypeComboBox;
    QLabel *label_32;
    QTextEdit *skillDescEdit;
    QComboBox *skillDescLangComboBox;
    QPushButton *skillDescCopyButton;
    QLabel *label_83;
    QComboBox *skillTransComboBox;
    QLabel *label_84;
    QLineEdit *skillTransNameEdit;
    QComboBox *skillTransLangComboBox;
    QPushButton *skillTransCopyButton;
    QPushButton *skillTransAddButton;
    QPushButton *skillTransRemoveButton;
    QPushButton *guidCopyButton;
    QLabel *label_113;
    QTextEdit *skillHowEdit;
    QComboBox *skillHowLangComboBox;
    QPushButton *skillHowCopyButton;
    QWidget *filesTab;
    QLabel *label_7;
    QLabel *label_8;
    QLabel *label_9;
    QLineEdit *addDataEdit;
    QPushButton *addEditButton;
    QPushButton *skillFilesButton;
    QLineEdit *skillFilesEdit;
    QWidget *cusTab;
    QLabel *label_10;
    QLineEdit *cusNameEdit;
    QLabel *label_11;
    QCheckBox *cusHumCheck;
    QCheckBox *cusHufCheck;
    QCheckBox *cusSymCheck;
    QCheckBox *cusSyfCheck;
    QCheckBox *cusNmcCheck;
    QCheckBox *cusFriCheck;
    QCheckBox *cusMamCheck;
    QCheckBox *cusMafCheck;
    QLabel *label_12;
    QLineEdit *cusTypeEdit;
    QLabel *label_13;
    QLineEdit *cusU0EEdit;
    QLabel *label_14;
    QLineEdit *cusPartsetEdit;
    QLabel *label_15;
    QLineEdit *cusU12Edit;
    QLineEdit *cusEanEdit;
    QLabel *label_16;
    QLineEdit *cusCamEanEdit;
    QLabel *label_17;
    QLabel *label_18;
    QLineEdit *cusEepkEdit;
    QLineEdit *cusAcbSeEdit;
    QLineEdit *cusAcbVoxEdit;
    QLabel *label_21;
    QLineEdit *cusBacEdit;
    QLabel *label_22;
    QLineEdit *cusBcmEdit;
    QLabel *label_23;
    QLineEdit *cusU30Edit;
    QLabel *label_24;
    QLineEdit *cusU32Edit;
    QLabel *label_25;
    QLineEdit *cusU34Edit;
    QLabel *label_26;
    QLineEdit *cusU36Edit;
    QLabel *label_27;
    QLineEdit *cusPupEdit;
    QLabel *label_28;
    QLineEdit *cusAuraEdit;
    QLineEdit *cusModelEdit;
    QLabel *label_30;
    QLineEdit *cusChangeSSEdit;
    QLabel *label_31;
    QLineEdit *cusNumTransEdit;
    QToolButton *cusCopyButton;
    QPushButton *cusAcbSeButton;
    QPushButton *cusAcbVoxButton;
    QPushButton *cusModelButton;
    QLineEdit *cusU44Edit;
    QLabel *label_107;
    QLineEdit *cusU48Edit;
    QLabel *label_108;
    QWidget *idbTab;
    QLabel *label_20;
    QCheckBox *idbHumCheck;
    QCheckBox *idbNmcCheck;
    QCheckBox *idbSymCheck;
    QCheckBox *idbHufCheck;
    QLabel *label_19;
    QCheckBox *idbMamCheck;
    QCheckBox *idbMafCheck;
    QCheckBox *idbFriCheck;
    QCheckBox *idbSyfCheck;
    QLineEdit *idbStarsEdit;
    QLabel *label_33;
    QToolButton *idbCopyButton;
    QLineEdit *idbU0AEdit;
    QLabel *label_34;
    QLineEdit *idbU0CEdit;
    QLineEdit *idbU0EEdit;
    QLabel *label_35;
    QLabel *label_36;
    QLineEdit *idbBuyEdit;
    QLineEdit *idbSellEdit;
    QLabel *label_37;
    QLineEdit *idbTpEdit;
    QLineEdit *idbModelEdit;
    QLabel *label_38;
    QLabel *label_39;
    QLineEdit *idbU24Edit;
    QLineEdit *idbU28Edit;
    QLabel *label_40;
    QLabel *label_41;
    QLabel *label_42;
    QLineEdit *idbU2CEdit;
    QLabel *label_43;
    QPushButton *idbEff1Button;
    QPushButton *idbEff2Button;
    QPushButton *idbEff3Button;
    QLabel *label_44;
    QLabel *label_45;
    QCheckBox *idbEnableCheck;
    QLineEdit *idbNU0CEdit;
    QLabel *label_106;
    QWidget *pupTab;
    QCheckBox *pupEnableCheck;
    QToolButton *pupCopyButton;
    QLabel *label_46;
    QLabel *label_47;
    QLabel *label_48;
    QLabel *label_49;
    QLabel *label_50;
    QLabel *label_51;
    QLabel *label_52;
    QLabel *label_53;
    QLabel *label_54;
    QLabel *label_55;
    QLabel *label_56;
    QLabel *label_57;
    QLabel *label_58;
    QLineEdit *pupU04Edit;
    QLineEdit *pupU08Edit;
    QLineEdit *pupU0CEdit;
    QLineEdit *pupHeaEdit;
    QLineEdit *pupF14Edit;
    QLineEdit *pupKiEdit;
    QLineEdit *pupKiRecEdit;
    QLineEdit *pupStmEdit;
    QLineEdit *pupStmRecEdit;
    QLineEdit *pupEnStaErEdit;
    QLineEdit *pupStaErEdit;
    QLineEdit *pupF30Edit;
    QLineEdit *pupAtkEdit;
    QLabel *label_59;
    QLabel *label_60;
    QLabel *label_61;
    QLabel *label_62;
    QLabel *label_63;
    QLabel *label_64;
    QLabel *label_65;
    QLabel *label_66;
    QLabel *label_67;
    QLabel *label_68;
    QLabel *label_69;
    QLabel *label_70;
    QLabel *label_71;
    QLineEdit *pupBasicKiAtkEdit;
    QLineEdit *pupStrEdit;
    QLineEdit *pupBlaEdit;
    QLineEdit *pupAtkDmgEdit;
    QLineEdit *pupKiDmgEdit;
    QLineEdit *pupStrDmgEdit;
    QLineEdit *pupBlaDmgEdit;
    QLineEdit *pupGroundSpeedEdit;
    QLineEdit *pupAirSpeedEdit;
    QLineEdit *pupBoostSpeedEdit;
    QLineEdit *pupDashSpeedEdit;
    QLineEdit *pupF64Edit;
    QLineEdit *pupF68Edit;
    QLabel *label_72;
    QLineEdit *pupF6CEdit;
    QLabel *label_73;
    QLabel *label_74;
    QLabel *label_75;
    QLabel *label_76;
    QLabel *label_77;
    QLabel *label_78;
    QLabel *label_79;
    QLabel *label_80;
    QLabel *label_81;
    QLabel *label_82;
    QLineEdit *pupF70Edit;
    QLineEdit *pupF74Edit;
    QLineEdit *pupF78Edit;
    QLineEdit *pupF7CEdit;
    QLineEdit *pupF80Edit;
    QLineEdit *pupF84Edit;
    QLineEdit *pupF88Edit;
    QLineEdit *pupF8CEdit;
    QLineEdit *pupF90Edit;
    QLineEdit *pupF94Edit;
    QPushButton *pupAddButton;
    QPushButton *pupRemoveButton;
    QComboBox *pupComboBox;
    QWidget *auraTab;
    QPushButton *auraAddButton;
    QCheckBox *auraEnableCheck;
    QComboBox *auraComboBox;
    QPushButton *auraRemoveButton;
    QLabel *label_85;
    QLabel *label_86;
    QToolButton *auraCopyButton;
    QToolButton *auraPatchCopyButton;
    QLabel *label_87;
    QLineEdit *auraIdEdit;
    QCheckBox *auraCustomCheck;
    QLabel *label_88;
    QLineEdit *auraEf0Edit;
    QLabel *label_89;
    QLineEdit *auraEf2Edit;
    QLabel *label_90;
    QLineEdit *auraEf4Edit;
    QLabel *label_91;
    QLineEdit *auraEf6Edit;
    QLabel *label_92;
    QLineEdit *auraEf1Edit;
    QLabel *label_93;
    QLineEdit *auraEf3Edit;
    QLabel *label_94;
    QLineEdit *auraEf5Edit;
    QLabel *label_95;
    QLineEdit *auraBH11Edit;
    QLabel *label_96;
    QLineEdit *auraInt2Edit;
    QLabel *label_97;
    QLineEdit *auraBH10Edit;
    QLineEdit *auraInt3Edit;
    QLabel *label_98;
    QCheckBox *auraTeleportCheck;
    QLabel *label_99;
    QLineEdit *auraBH13Edit;
    QLabel *label_29;
    QLineEdit *auraBH66Edit;
    QLabel *label_102;
    QLineEdit *auraHairColorEdit;
    QToolButton *auraGetHairColorButton;
    QLabel *label_103;
    QComboBox *auraRemoveHairAccCombo;
    QLabel *label_104;
    QLineEdit *auraEyesColorEdit;
    QToolButton *auraGetEyesColorButton;
    QLineEdit *auraMoreColorsEdit;
    QLabel *label_109;
    QToolButton *auraAddMoreColorButton;
    QLineEdit *auraBpeEdit;
    QLabel *label_110;
    QCheckBox *auraBpeFlag1Check;
    QCheckBox *auraBpeFlag2Check;
    QToolButton *aurBpeButton;
    QLineEdit *auraBH64Edit;
    QLabel *label_111;
    QLabel *label_112;
    QWidget *bcsTab;
    QLabel *label_100;
    QLabel *label_101;
    QLineEdit *bcsAttachmentEdit;
    QPushButton *bcsAttachmentSetButton;
    QPushButton *bcsAttachmentRemoveButton;
    QCheckBox *bcsBodyCheck;
    QPushButton *bcsBodyRemoveButton;
    QPushButton *bcsBodyAddButton;
    QComboBox *bcsBodyComboBox;
    QLabel *bcsBodyId;
    QLabel *label_105;
    QComboBox *bcsBodyRaceComboBox;
    QTextEdit *bcsBodyEdit;
    QMenuBar *menuBar;
    QMenu *menuFile;
    QMenu *menuHelp;
    QMenu *menuTools;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(661, 840);
        actionOpen = new QAction(MainWindow);
        actionOpen->setObjectName(QStringLiteral("actionOpen"));
        actionSave = new QAction(MainWindow);
        actionSave->setObjectName(QStringLiteral("actionSave"));
        actionExit = new QAction(MainWindow);
        actionExit->setObjectName(QStringLiteral("actionExit"));
        actionAbout = new QAction(MainWindow);
        actionAbout->setObjectName(QStringLiteral("actionAbout"));
        actionFromGameCus = new QAction(MainWindow);
        actionFromGameCus->setObjectName(QStringLiteral("actionFromGameCus"));
        actionFromExternalCus = new QAction(MainWindow);
        actionFromExternalCus->setObjectName(QStringLiteral("actionFromExternalCus"));
        actionImportSkillDir = new QAction(MainWindow);
        actionImportSkillDir->setObjectName(QStringLiteral("actionImportSkillDir"));
        actionFromGameIdb = new QAction(MainWindow);
        actionFromGameIdb->setObjectName(QStringLiteral("actionFromGameIdb"));
        actionFromGamePup = new QAction(MainWindow);
        actionFromGamePup->setObjectName(QStringLiteral("actionFromGamePup"));
        actionFromExternalPup = new QAction(MainWindow);
        actionFromExternalPup->setObjectName(QStringLiteral("actionFromExternalPup"));
        actionFromPupSkillUsage = new QAction(MainWindow);
        actionFromPupSkillUsage->setObjectName(QStringLiteral("actionFromPupSkillUsage"));
        actionFromGameAur = new QAction(MainWindow);
        actionFromGameAur->setObjectName(QStringLiteral("actionFromGameAur"));
        actionFromExternalAur = new QAction(MainWindow);
        actionFromExternalAur->setObjectName(QStringLiteral("actionFromExternalAur"));
        actionFromAuraSkillUsage = new QAction(MainWindow);
        actionFromAuraSkillUsage->setObjectName(QStringLiteral("actionFromAuraSkillUsage"));
        actionFromAuraCharUsage = new QAction(MainWindow);
        actionFromAuraCharUsage->setObjectName(QStringLiteral("actionFromAuraCharUsage"));
        actionFromAuraPatchSkillUsage = new QAction(MainWindow);
        actionFromAuraPatchSkillUsage->setObjectName(QStringLiteral("actionFromAuraPatchSkillUsage"));
        actionFromHumBcs = new QAction(MainWindow);
        actionFromHumBcs->setObjectName(QStringLiteral("actionFromHumBcs"));
        actionFromHufBcs = new QAction(MainWindow);
        actionFromHufBcs->setObjectName(QStringLiteral("actionFromHufBcs"));
        actionFromBcsFile = new QAction(MainWindow);
        actionFromBcsFile->setObjectName(QStringLiteral("actionFromBcsFile"));
        actionFromHumBcsEyes = new QAction(MainWindow);
        actionFromHumBcsEyes->setObjectName(QStringLiteral("actionFromHumBcsEyes"));
        actionFromHufBcsEyes = new QAction(MainWindow);
        actionFromHufBcsEyes->setObjectName(QStringLiteral("actionFromHufBcsEyes"));
        actionFromNmcBcsEyes = new QAction(MainWindow);
        actionFromNmcBcsEyes->setObjectName(QStringLiteral("actionFromNmcBcsEyes"));
        actionFromFriBcsEyes = new QAction(MainWindow);
        actionFromFriBcsEyes->setObjectName(QStringLiteral("actionFromFriBcsEyes"));
        actionFromMamBcsEyes = new QAction(MainWindow);
        actionFromMamBcsEyes->setObjectName(QStringLiteral("actionFromMamBcsEyes"));
        actionFromMafBcsEyes = new QAction(MainWindow);
        actionFromMafBcsEyes->setObjectName(QStringLiteral("actionFromMafBcsEyes"));
        actionFromBcsFileEyes = new QAction(MainWindow);
        actionFromBcsFileEyes->setObjectName(QStringLiteral("actionFromBcsFileEyes"));
        actionFromHumBcsMore = new QAction(MainWindow);
        actionFromHumBcsMore->setObjectName(QStringLiteral("actionFromHumBcsMore"));
        actionFromHufBcsMore = new QAction(MainWindow);
        actionFromHufBcsMore->setObjectName(QStringLiteral("actionFromHufBcsMore"));
        actionFromNmcBcsMore = new QAction(MainWindow);
        actionFromNmcBcsMore->setObjectName(QStringLiteral("actionFromNmcBcsMore"));
        actionFromFriBcsMore = new QAction(MainWindow);
        actionFromFriBcsMore->setObjectName(QStringLiteral("actionFromFriBcsMore"));
        actionFromMamBcsMore = new QAction(MainWindow);
        actionFromMamBcsMore->setObjectName(QStringLiteral("actionFromMamBcsMore"));
        actionFromMafBcsMore = new QAction(MainWindow);
        actionFromMafBcsMore->setObjectName(QStringLiteral("actionFromMafBcsMore"));
        actionFromBcsFileMore = new QAction(MainWindow);
        actionFromBcsFileMore->setObjectName(QStringLiteral("actionFromBcsFileMore"));
        actionFromCmnBpe = new QAction(MainWindow);
        actionFromCmnBpe->setObjectName(QStringLiteral("actionFromCmnBpe"));
        actionFromCmnBpeBO = new QAction(MainWindow);
        actionFromCmnBpeBO->setObjectName(QStringLiteral("actionFromCmnBpeBO"));
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        tabWidget = new QTabWidget(centralWidget);
        tabWidget->setObjectName(QStringLiteral("tabWidget"));
        tabWidget->setGeometry(QRect(20, 20, 621, 751));
        tabWidget->setAutoFillBackground(true);
        modInfoTab = new QWidget();
        modInfoTab->setObjectName(QStringLiteral("modInfoTab"));
        modInfoTab->setAutoFillBackground(true);
        modNameEdit = new QLineEdit(modInfoTab);
        modNameEdit->setObjectName(QStringLiteral("modNameEdit"));
        modNameEdit->setGeometry(QRect(70, 21, 315, 20));
        label_2 = new QLabel(modInfoTab);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(20, 103, 47, 13));
        guidButton = new QPushButton(modInfoTab);
        guidButton->setObjectName(QStringLiteral("guidButton"));
        guidButton->setGeometry(QRect(300, 140, 91, 23));
        label = new QLabel(modInfoTab);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(28, 23, 51, 16));
        modVersionEdit = new QLineEdit(modInfoTab);
        modVersionEdit->setObjectName(QStringLiteral("modVersionEdit"));
        modVersionEdit->setGeometry(QRect(70, 101, 61, 20));
        modAuthorEdit = new QLineEdit(modInfoTab);
        modAuthorEdit->setObjectName(QStringLiteral("modAuthorEdit"));
        modAuthorEdit->setGeometry(QRect(70, 61, 215, 20));
        label_5 = new QLabel(modInfoTab);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(7, 223, 101, 16));
        label_4 = new QLabel(modInfoTab);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(31, 143, 31, 16));
        modGuidEdit = new QLineEdit(modInfoTab);
        modGuidEdit->setObjectName(QStringLiteral("modGuidEdit"));
        modGuidEdit->setEnabled(false);
        modGuidEdit->setGeometry(QRect(70, 141, 215, 20));
        skillNameLangComboBox = new QComboBox(modInfoTab);
        skillNameLangComboBox->setObjectName(QStringLiteral("skillNameLangComboBox"));
        skillNameLangComboBox->setGeometry(QRect(400, 220, 91, 22));
        label_3 = new QLabel(modInfoTab);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(22, 63, 47, 13));
        skillNameEdit = new QLineEdit(modInfoTab);
        skillNameEdit->setObjectName(QStringLiteral("skillNameEdit"));
        skillNameEdit->setGeometry(QRect(70, 221, 315, 20));
        skillNameCopyButton = new QPushButton(modInfoTab);
        skillNameCopyButton->setObjectName(QStringLiteral("skillNameCopyButton"));
        skillNameCopyButton->setGeometry(QRect(500, 220, 95, 23));
        label_6 = new QLabel(modInfoTab);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(11, 183, 47, 13));
        skillTypeComboBox = new QComboBox(modInfoTab);
        skillTypeComboBox->setObjectName(QStringLiteral("skillTypeComboBox"));
        skillTypeComboBox->setGeometry(QRect(70, 180, 121, 22));
        label_32 = new QLabel(modInfoTab);
        label_32->setObjectName(QStringLiteral("label_32"));
        label_32->setGeometry(QRect(24, 263, 71, 16));
        skillDescEdit = new QTextEdit(modInfoTab);
        skillDescEdit->setObjectName(QStringLiteral("skillDescEdit"));
        skillDescEdit->setGeometry(QRect(70, 263, 315, 91));
        skillDescLangComboBox = new QComboBox(modInfoTab);
        skillDescLangComboBox->setObjectName(QStringLiteral("skillDescLangComboBox"));
        skillDescLangComboBox->setGeometry(QRect(400, 263, 91, 22));
        skillDescCopyButton = new QPushButton(modInfoTab);
        skillDescCopyButton->setObjectName(QStringLiteral("skillDescCopyButton"));
        skillDescCopyButton->setGeometry(QRect(500, 263, 95, 23));
        label_83 = new QLabel(modInfoTab);
        label_83->setObjectName(QStringLiteral("label_83"));
        label_83->setGeometry(QRect(5, 390, 131, 16));
        skillTransComboBox = new QComboBox(modInfoTab);
        skillTransComboBox->setObjectName(QStringLiteral("skillTransComboBox"));
        skillTransComboBox->setGeometry(QRect(130, 387, 111, 22));
        label_84 = new QLabel(modInfoTab);
        label_84->setObjectName(QStringLiteral("label_84"));
        label_84->setGeometry(QRect(25, 430, 47, 13));
        skillTransNameEdit = new QLineEdit(modInfoTab);
        skillTransNameEdit->setObjectName(QStringLiteral("skillTransNameEdit"));
        skillTransNameEdit->setGeometry(QRect(70, 428, 315, 20));
        skillTransLangComboBox = new QComboBox(modInfoTab);
        skillTransLangComboBox->setObjectName(QStringLiteral("skillTransLangComboBox"));
        skillTransLangComboBox->setGeometry(QRect(400, 427, 91, 22));
        skillTransCopyButton = new QPushButton(modInfoTab);
        skillTransCopyButton->setObjectName(QStringLiteral("skillTransCopyButton"));
        skillTransCopyButton->setGeometry(QRect(500, 427, 95, 23));
        skillTransAddButton = new QPushButton(modInfoTab);
        skillTransAddButton->setObjectName(QStringLiteral("skillTransAddButton"));
        skillTransAddButton->setGeometry(QRect(260, 387, 75, 23));
        skillTransRemoveButton = new QPushButton(modInfoTab);
        skillTransRemoveButton->setObjectName(QStringLiteral("skillTransRemoveButton"));
        skillTransRemoveButton->setGeometry(QRect(340, 387, 75, 23));
        guidCopyButton = new QPushButton(modInfoTab);
        guidCopyButton->setObjectName(QStringLiteral("guidCopyButton"));
        guidCopyButton->setGeometry(QRect(405, 140, 95, 23));
        label_113 = new QLabel(modInfoTab);
        label_113->setObjectName(QStringLiteral("label_113"));
        label_113->setGeometry(QRect(29, 470, 49, 16));
        skillHowEdit = new QTextEdit(modInfoTab);
        skillHowEdit->setObjectName(QStringLiteral("skillHowEdit"));
        skillHowEdit->setGeometry(QRect(70, 470, 315, 91));
        skillHowLangComboBox = new QComboBox(modInfoTab);
        skillHowLangComboBox->setObjectName(QStringLiteral("skillHowLangComboBox"));
        skillHowLangComboBox->setGeometry(QRect(400, 470, 91, 22));
        skillHowCopyButton = new QPushButton(modInfoTab);
        skillHowCopyButton->setObjectName(QStringLiteral("skillHowCopyButton"));
        skillHowCopyButton->setGeometry(QRect(500, 470, 95, 23));
        tabWidget->addTab(modInfoTab, QString());
        filesTab = new QWidget();
        filesTab->setObjectName(QStringLiteral("filesTab"));
        filesTab->setAutoFillBackground(true);
        label_7 = new QLabel(filesTab);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(49, 23, 51, 16));
        label_8 = new QLabel(filesTab);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(10, 63, 101, 16));
        label_9 = new QLabel(filesTab);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(10, 103, 381, 16));
        addDataEdit = new QLineEdit(filesTab);
        addDataEdit->setObjectName(QStringLiteral("addDataEdit"));
        addDataEdit->setGeometry(QRect(100, 61, 425, 20));
        addEditButton = new QPushButton(filesTab);
        addEditButton->setObjectName(QStringLiteral("addEditButton"));
        addEditButton->setGeometry(QRect(535, 60, 61, 23));
        skillFilesButton = new QPushButton(filesTab);
        skillFilesButton->setObjectName(QStringLiteral("skillFilesButton"));
        skillFilesButton->setGeometry(QRect(535, 20, 61, 23));
        skillFilesEdit = new QLineEdit(filesTab);
        skillFilesEdit->setObjectName(QStringLiteral("skillFilesEdit"));
        skillFilesEdit->setGeometry(QRect(100, 21, 425, 20));
        tabWidget->addTab(filesTab, QString());
        cusTab = new QWidget();
        cusTab->setObjectName(QStringLiteral("cusTab"));
        cusTab->setAutoFillBackground(true);
        label_10 = new QLabel(cusTab);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(27, 23, 47, 13));
        cusNameEdit = new QLineEdit(cusTab);
        cusNameEdit->setObjectName(QStringLiteral("cusNameEdit"));
        cusNameEdit->setGeometry(QRect(70, 21, 75, 20));
        label_11 = new QLabel(cusTab);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(10, 63, 61, 16));
        cusHumCheck = new QCheckBox(cusTab);
        cusHumCheck->setObjectName(QStringLiteral("cusHumCheck"));
        cusHumCheck->setGeometry(QRect(70, 63, 51, 17));
        cusHufCheck = new QCheckBox(cusTab);
        cusHufCheck->setObjectName(QStringLiteral("cusHufCheck"));
        cusHufCheck->setGeometry(QRect(130, 63, 51, 17));
        cusSymCheck = new QCheckBox(cusTab);
        cusSymCheck->setObjectName(QStringLiteral("cusSymCheck"));
        cusSymCheck->setGeometry(QRect(190, 63, 51, 17));
        cusSyfCheck = new QCheckBox(cusTab);
        cusSyfCheck->setObjectName(QStringLiteral("cusSyfCheck"));
        cusSyfCheck->setGeometry(QRect(250, 63, 41, 17));
        cusNmcCheck = new QCheckBox(cusTab);
        cusNmcCheck->setObjectName(QStringLiteral("cusNmcCheck"));
        cusNmcCheck->setGeometry(QRect(310, 63, 51, 17));
        cusFriCheck = new QCheckBox(cusTab);
        cusFriCheck->setObjectName(QStringLiteral("cusFriCheck"));
        cusFriCheck->setGeometry(QRect(370, 63, 51, 17));
        cusMamCheck = new QCheckBox(cusTab);
        cusMamCheck->setObjectName(QStringLiteral("cusMamCheck"));
        cusMamCheck->setGeometry(QRect(430, 63, 51, 17));
        cusMafCheck = new QCheckBox(cusTab);
        cusMafCheck->setObjectName(QStringLiteral("cusMafCheck"));
        cusMafCheck->setGeometry(QRect(490, 63, 51, 17));
        label_12 = new QLabel(cusTab);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(30, 103, 47, 13));
        cusTypeEdit = new QLineEdit(cusTab);
        cusTypeEdit->setObjectName(QStringLiteral("cusTypeEdit"));
        cusTypeEdit->setGeometry(QRect(75, 101, 75, 20));
        label_13 = new QLabel(cusTab);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(9, 143, 61, 16));
        cusU0EEdit = new QLineEdit(cusTab);
        cusU0EEdit->setObjectName(QStringLiteral("cusU0EEdit"));
        cusU0EEdit->setGeometry(QRect(75, 141, 75, 20));
        label_14 = new QLabel(cusTab);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(21, 183, 47, 13));
        cusPartsetEdit = new QLineEdit(cusTab);
        cusPartsetEdit->setObjectName(QStringLiteral("cusPartsetEdit"));
        cusPartsetEdit->setGeometry(QRect(75, 181, 75, 20));
        label_15 = new QLabel(cusTab);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(10, 223, 51, 16));
        cusU12Edit = new QLineEdit(cusTab);
        cusU12Edit->setObjectName(QStringLiteral("cusU12Edit"));
        cusU12Edit->setGeometry(QRect(75, 221, 75, 20));
        cusEanEdit = new QLineEdit(cusTab);
        cusEanEdit->setObjectName(QStringLiteral("cusEanEdit"));
        cusEanEdit->setGeometry(QRect(75, 261, 200, 20));
        label_16 = new QLabel(cusTab);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(35, 263, 47, 13));
        cusCamEanEdit = new QLineEdit(cusTab);
        cusCamEanEdit->setObjectName(QStringLiteral("cusCamEanEdit"));
        cusCamEanEdit->setGeometry(QRect(75, 301, 200, 20));
        label_17 = new QLabel(cusTab);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(12, 303, 47, 13));
        label_18 = new QLabel(cusTab);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(30, 343, 47, 13));
        cusEepkEdit = new QLineEdit(cusTab);
        cusEepkEdit->setObjectName(QStringLiteral("cusEepkEdit"));
        cusEepkEdit->setGeometry(QRect(75, 341, 200, 20));
        cusAcbSeEdit = new QLineEdit(cusTab);
        cusAcbSeEdit->setObjectName(QStringLiteral("cusAcbSeEdit"));
        cusAcbSeEdit->setGeometry(QRect(75, 381, 200, 20));
        cusAcbVoxEdit = new QLineEdit(cusTab);
        cusAcbVoxEdit->setObjectName(QStringLiteral("cusAcbVoxEdit"));
        cusAcbVoxEdit->setGeometry(QRect(75, 421, 200, 20));
        label_21 = new QLabel(cusTab);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(35, 463, 41, 20));
        cusBacEdit = new QLineEdit(cusTab);
        cusBacEdit->setObjectName(QStringLiteral("cusBacEdit"));
        cusBacEdit->setGeometry(QRect(75, 461, 200, 20));
        label_22 = new QLabel(cusTab);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setGeometry(QRect(370, 103, 47, 13));
        cusBcmEdit = new QLineEdit(cusTab);
        cusBcmEdit->setObjectName(QStringLiteral("cusBcmEdit"));
        cusBcmEdit->setGeometry(QRect(405, 101, 200, 20));
        label_23 = new QLabel(cusTab);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(363, 143, 51, 16));
        cusU30Edit = new QLineEdit(cusTab);
        cusU30Edit->setObjectName(QStringLiteral("cusU30Edit"));
        cusU30Edit->setGeometry(QRect(405, 141, 75, 20));
        label_24 = new QLabel(cusTab);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(338, 183, 71, 16));
        cusU32Edit = new QLineEdit(cusTab);
        cusU32Edit->setObjectName(QStringLiteral("cusU32Edit"));
        cusU32Edit->setGeometry(QRect(405, 181, 75, 20));
        label_25 = new QLabel(cusTab);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(338, 223, 61, 16));
        cusU34Edit = new QLineEdit(cusTab);
        cusU34Edit->setObjectName(QStringLiteral("cusU34Edit"));
        cusU34Edit->setGeometry(QRect(405, 221, 75, 20));
        label_26 = new QLabel(cusTab);
        label_26->setObjectName(QStringLiteral("label_26"));
        label_26->setGeometry(QRect(342, 263, 61, 16));
        cusU36Edit = new QLineEdit(cusTab);
        cusU36Edit->setObjectName(QStringLiteral("cusU36Edit"));
        cusU36Edit->setGeometry(QRect(405, 261, 75, 20));
        label_27 = new QLabel(cusTab);
        label_27->setObjectName(QStringLiteral("label_27"));
        label_27->setGeometry(QRect(370, 303, 31, 16));
        cusPupEdit = new QLineEdit(cusTab);
        cusPupEdit->setObjectName(QStringLiteral("cusPupEdit"));
        cusPupEdit->setGeometry(QRect(405, 301, 75, 20));
        label_28 = new QLabel(cusTab);
        label_28->setObjectName(QStringLiteral("label_28"));
        label_28->setGeometry(QRect(298, 343, 101, 20));
        cusAuraEdit = new QLineEdit(cusTab);
        cusAuraEdit->setObjectName(QStringLiteral("cusAuraEdit"));
        cusAuraEdit->setGeometry(QRect(405, 341, 75, 20));
        cusModelEdit = new QLineEdit(cusTab);
        cusModelEdit->setObjectName(QStringLiteral("cusModelEdit"));
        cusModelEdit->setGeometry(QRect(405, 381, 75, 20));
        label_30 = new QLabel(cusTab);
        label_30->setObjectName(QStringLiteral("label_30"));
        label_30->setGeometry(QRect(323, 423, 81, 16));
        cusChangeSSEdit = new QLineEdit(cusTab);
        cusChangeSSEdit->setObjectName(QStringLiteral("cusChangeSSEdit"));
        cusChangeSSEdit->setGeometry(QRect(405, 421, 75, 20));
        label_31 = new QLabel(cusTab);
        label_31->setObjectName(QStringLiteral("label_31"));
        label_31->setGeometry(QRect(305, 463, 101, 16));
        cusNumTransEdit = new QLineEdit(cusTab);
        cusNumTransEdit->setObjectName(QStringLiteral("cusNumTransEdit"));
        cusNumTransEdit->setGeometry(QRect(405, 461, 75, 20));
        cusCopyButton = new QToolButton(cusTab);
        cusCopyButton->setObjectName(QStringLiteral("cusCopyButton"));
        cusCopyButton->setGeometry(QRect(510, 23, 75, 23));
        cusCopyButton->setPopupMode(QToolButton::InstantPopup);
        cusCopyButton->setToolButtonStyle(Qt::ToolButtonTextOnly);
        cusAcbSeButton = new QPushButton(cusTab);
        cusAcbSeButton->setObjectName(QStringLiteral("cusAcbSeButton"));
        cusAcbSeButton->setGeometry(QRect(10, 383, 61, 23));
        cusAcbSeButton->setFlat(true);
        cusAcbVoxButton = new QPushButton(cusTab);
        cusAcbVoxButton->setObjectName(QStringLiteral("cusAcbVoxButton"));
        cusAcbVoxButton->setGeometry(QRect(4, 423, 71, 23));
        cusAcbVoxButton->setFlat(true);
        cusModelButton = new QPushButton(cusTab);
        cusModelButton->setObjectName(QStringLiteral("cusModelButton"));
        cusModelButton->setGeometry(QRect(338, 380, 75, 23));
        cusModelButton->setFlat(true);
        cusU44Edit = new QLineEdit(cusTab);
        cusU44Edit->setObjectName(QStringLiteral("cusU44Edit"));
        cusU44Edit->setGeometry(QRect(75, 501, 75, 20));
        label_107 = new QLabel(cusTab);
        label_107->setObjectName(QStringLiteral("label_107"));
        label_107->setGeometry(QRect(30, 503, 47, 13));
        cusU48Edit = new QLineEdit(cusTab);
        cusU48Edit->setObjectName(QStringLiteral("cusU48Edit"));
        cusU48Edit->setGeometry(QRect(405, 501, 75, 22));
        label_108 = new QLabel(cusTab);
        label_108->setObjectName(QStringLiteral("label_108"));
        label_108->setGeometry(QRect(360, 503, 47, 16));
        tabWidget->addTab(cusTab, QString());
        idbTab = new QWidget();
        idbTab->setObjectName(QStringLiteral("idbTab"));
        idbTab->setAutoFillBackground(true);
        label_20 = new QLabel(idbTab);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(79, 110, 31, 16));
        idbHumCheck = new QCheckBox(idbTab);
        idbHumCheck->setObjectName(QStringLiteral("idbHumCheck"));
        idbHumCheck->setGeometry(QRect(70, 70, 51, 17));
        idbNmcCheck = new QCheckBox(idbTab);
        idbNmcCheck->setObjectName(QStringLiteral("idbNmcCheck"));
        idbNmcCheck->setGeometry(QRect(310, 70, 51, 17));
        idbSymCheck = new QCheckBox(idbTab);
        idbSymCheck->setObjectName(QStringLiteral("idbSymCheck"));
        idbSymCheck->setGeometry(QRect(190, 70, 51, 17));
        idbHufCheck = new QCheckBox(idbTab);
        idbHufCheck->setObjectName(QStringLiteral("idbHufCheck"));
        idbHufCheck->setGeometry(QRect(130, 70, 51, 17));
        label_19 = new QLabel(idbTab);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(10, 70, 61, 16));
        idbMamCheck = new QCheckBox(idbTab);
        idbMamCheck->setObjectName(QStringLiteral("idbMamCheck"));
        idbMamCheck->setGeometry(QRect(430, 70, 51, 17));
        idbMafCheck = new QCheckBox(idbTab);
        idbMafCheck->setObjectName(QStringLiteral("idbMafCheck"));
        idbMafCheck->setGeometry(QRect(490, 70, 51, 17));
        idbFriCheck = new QCheckBox(idbTab);
        idbFriCheck->setObjectName(QStringLiteral("idbFriCheck"));
        idbFriCheck->setGeometry(QRect(370, 70, 51, 17));
        idbSyfCheck = new QCheckBox(idbTab);
        idbSyfCheck->setObjectName(QStringLiteral("idbSyfCheck"));
        idbSyfCheck->setGeometry(QRect(250, 70, 51, 17));
        idbStarsEdit = new QLineEdit(idbTab);
        idbStarsEdit->setObjectName(QStringLiteral("idbStarsEdit"));
        idbStarsEdit->setGeometry(QRect(120, 108, 75, 20));
        label_33 = new QLabel(idbTab);
        label_33->setObjectName(QStringLiteral("label_33"));
        label_33->setGeometry(QRect(260, 110, 47, 13));
        idbCopyButton = new QToolButton(idbTab);
        idbCopyButton->setObjectName(QStringLiteral("idbCopyButton"));
        idbCopyButton->setGeometry(QRect(510, 23, 75, 23));
        idbCopyButton->setPopupMode(QToolButton::InstantPopup);
        idbCopyButton->setToolButtonStyle(Qt::ToolButtonTextOnly);
        idbU0AEdit = new QLineEdit(idbTab);
        idbU0AEdit->setObjectName(QStringLiteral("idbU0AEdit"));
        idbU0AEdit->setGeometry(QRect(300, 108, 75, 20));
        label_34 = new QLabel(idbTab);
        label_34->setObjectName(QStringLiteral("label_34"));
        label_34->setGeometry(QRect(0, 150, 111, 16));
        idbU0CEdit = new QLineEdit(idbTab);
        idbU0CEdit->setObjectName(QStringLiteral("idbU0CEdit"));
        idbU0CEdit->setGeometry(QRect(120, 148, 75, 20));
        idbU0EEdit = new QLineEdit(idbTab);
        idbU0EEdit->setObjectName(QStringLiteral("idbU0EEdit"));
        idbU0EEdit->setGeometry(QRect(300, 148, 75, 20));
        label_35 = new QLabel(idbTab);
        label_35->setObjectName(QStringLiteral("label_35"));
        label_35->setGeometry(QRect(260, 150, 47, 13));
        label_36 = new QLabel(idbTab);
        label_36->setObjectName(QStringLiteral("label_36"));
        label_36->setGeometry(QRect(85, 190, 41, 16));
        idbBuyEdit = new QLineEdit(idbTab);
        idbBuyEdit->setObjectName(QStringLiteral("idbBuyEdit"));
        idbBuyEdit->setGeometry(QRect(120, 188, 75, 20));
        idbSellEdit = new QLineEdit(idbTab);
        idbSellEdit->setObjectName(QStringLiteral("idbSellEdit"));
        idbSellEdit->setGeometry(QRect(300, 188, 75, 20));
        label_37 = new QLabel(idbTab);
        label_37->setObjectName(QStringLiteral("label_37"));
        label_37->setGeometry(QRect(269, 190, 31, 16));
        idbTpEdit = new QLineEdit(idbTab);
        idbTpEdit->setObjectName(QStringLiteral("idbTpEdit"));
        idbTpEdit->setGeometry(QRect(120, 228, 75, 20));
        idbModelEdit = new QLineEdit(idbTab);
        idbModelEdit->setObjectName(QStringLiteral("idbModelEdit"));
        idbModelEdit->setGeometry(QRect(300, 228, 75, 20));
        label_38 = new QLabel(idbTab);
        label_38->setObjectName(QStringLiteral("label_38"));
        label_38->setGeometry(QRect(90, 230, 31, 16));
        label_39 = new QLabel(idbTab);
        label_39->setObjectName(QStringLiteral("label_39"));
        label_39->setGeometry(QRect(257, 230, 47, 13));
        idbU24Edit = new QLineEdit(idbTab);
        idbU24Edit->setObjectName(QStringLiteral("idbU24Edit"));
        idbU24Edit->setGeometry(QRect(120, 268, 75, 20));
        idbU28Edit = new QLineEdit(idbTab);
        idbU28Edit->setObjectName(QStringLiteral("idbU28Edit"));
        idbU28Edit->setGeometry(QRect(300, 268, 75, 20));
        label_40 = new QLabel(idbTab);
        label_40->setObjectName(QStringLiteral("label_40"));
        label_40->setGeometry(QRect(78, 270, 41, 16));
        label_41 = new QLabel(idbTab);
        label_41->setObjectName(QStringLiteral("label_41"));
        label_41->setGeometry(QRect(260, 270, 41, 16));
        label_42 = new QLabel(idbTab);
        label_42->setObjectName(QStringLiteral("label_42"));
        label_42->setGeometry(QRect(440, 270, 47, 13));
        idbU2CEdit = new QLineEdit(idbTab);
        idbU2CEdit->setObjectName(QStringLiteral("idbU2CEdit"));
        idbU2CEdit->setGeometry(QRect(480, 268, 75, 20));
        label_43 = new QLabel(idbTab);
        label_43->setObjectName(QStringLiteral("label_43"));
        label_43->setGeometry(QRect(66, 310, 47, 13));
        idbEff1Button = new QPushButton(idbTab);
        idbEff1Button->setObjectName(QStringLiteral("idbEff1Button"));
        idbEff1Button->setGeometry(QRect(120, 305, 75, 23));
        idbEff2Button = new QPushButton(idbTab);
        idbEff2Button->setObjectName(QStringLiteral("idbEff2Button"));
        idbEff2Button->setGeometry(QRect(300, 305, 75, 23));
        idbEff3Button = new QPushButton(idbTab);
        idbEff3Button->setObjectName(QStringLiteral("idbEff3Button"));
        idbEff3Button->setGeometry(QRect(480, 305, 75, 23));
        label_44 = new QLabel(idbTab);
        label_44->setObjectName(QStringLiteral("label_44"));
        label_44->setGeometry(QRect(247, 310, 47, 13));
        label_45 = new QLabel(idbTab);
        label_45->setObjectName(QStringLiteral("label_45"));
        label_45->setGeometry(QRect(427, 310, 47, 13));
        idbEnableCheck = new QCheckBox(idbTab);
        idbEnableCheck->setObjectName(QStringLiteral("idbEnableCheck"));
        idbEnableCheck->setGeometry(QRect(20, 23, 81, 17));
        idbNU0CEdit = new QLineEdit(idbTab);
        idbNU0CEdit->setObjectName(QStringLiteral("idbNU0CEdit"));
        idbNU0CEdit->setGeometry(QRect(480, 228, 75, 20));
        label_106 = new QLabel(idbTab);
        label_106->setObjectName(QStringLiteral("label_106"));
        label_106->setGeometry(QRect(437, 230, 47, 13));
        tabWidget->addTab(idbTab, QString());
        pupTab = new QWidget();
        pupTab->setObjectName(QStringLiteral("pupTab"));
        pupTab->setAutoFillBackground(true);
        pupEnableCheck = new QCheckBox(pupTab);
        pupEnableCheck->setObjectName(QStringLiteral("pupEnableCheck"));
        pupEnableCheck->setGeometry(QRect(20, 23, 81, 17));
        pupCopyButton = new QToolButton(pupTab);
        pupCopyButton->setObjectName(QStringLiteral("pupCopyButton"));
        pupCopyButton->setGeometry(QRect(510, 23, 75, 23));
        pupCopyButton->setPopupMode(QToolButton::InstantPopup);
        pupCopyButton->setToolButtonStyle(Qt::ToolButtonTextOnly);
        label_46 = new QLabel(pupTab);
        label_46->setObjectName(QStringLiteral("label_46"));
        label_46->setGeometry(QRect(89, 70, 47, 13));
        label_47 = new QLabel(pupTab);
        label_47->setObjectName(QStringLiteral("label_47"));
        label_47->setGeometry(QRect(50, 100, 81, 16));
        label_48 = new QLabel(pupTab);
        label_48->setObjectName(QStringLiteral("label_48"));
        label_48->setGeometry(QRect(50, 130, 81, 16));
        label_49 = new QLabel(pupTab);
        label_49->setObjectName(QStringLiteral("label_49"));
        label_49->setGeometry(QRect(94, 160, 47, 13));
        label_50 = new QLabel(pupTab);
        label_50->setObjectName(QStringLiteral("label_50"));
        label_50->setGeometry(QRect(90, 190, 47, 13));
        label_51 = new QLabel(pupTab);
        label_51->setObjectName(QStringLiteral("label_51"));
        label_51->setGeometry(QRect(104, 220, 21, 16));
        label_52 = new QLabel(pupTab);
        label_52->setObjectName(QStringLiteral("label_52"));
        label_52->setGeometry(QRect(59, 250, 71, 16));
        label_53 = new QLabel(pupTab);
        label_53->setObjectName(QStringLiteral("label_53"));
        label_53->setGeometry(QRect(93, 280, 47, 13));
        label_54 = new QLabel(pupTab);
        label_54->setObjectName(QStringLiteral("label_54"));
        label_54->setGeometry(QRect(29, 310, 101, 16));
        label_55 = new QLabel(pupTab);
        label_55->setObjectName(QStringLiteral("label_55"));
        label_55->setGeometry(QRect(7, 340, 121, 16));
        label_56 = new QLabel(pupTab);
        label_56->setObjectName(QStringLiteral("label_56"));
        label_56->setGeometry(QRect(40, 370, 91, 16));
        label_57 = new QLabel(pupTab);
        label_57->setObjectName(QStringLiteral("label_57"));
        label_57->setGeometry(QRect(87, 400, 47, 13));
        label_58 = new QLabel(pupTab);
        label_58->setObjectName(QStringLiteral("label_58"));
        label_58->setGeometry(QRect(92, 430, 47, 13));
        pupU04Edit = new QLineEdit(pupTab);
        pupU04Edit->setObjectName(QStringLiteral("pupU04Edit"));
        pupU04Edit->setGeometry(QRect(127, 68, 90, 20));
        pupU08Edit = new QLineEdit(pupTab);
        pupU08Edit->setObjectName(QStringLiteral("pupU08Edit"));
        pupU08Edit->setGeometry(QRect(127, 98, 90, 20));
        pupU0CEdit = new QLineEdit(pupTab);
        pupU0CEdit->setObjectName(QStringLiteral("pupU0CEdit"));
        pupU0CEdit->setGeometry(QRect(127, 128, 90, 20));
        pupHeaEdit = new QLineEdit(pupTab);
        pupHeaEdit->setObjectName(QStringLiteral("pupHeaEdit"));
        pupHeaEdit->setGeometry(QRect(127, 158, 90, 20));
        pupF14Edit = new QLineEdit(pupTab);
        pupF14Edit->setObjectName(QStringLiteral("pupF14Edit"));
        pupF14Edit->setGeometry(QRect(127, 188, 90, 20));
        pupKiEdit = new QLineEdit(pupTab);
        pupKiEdit->setObjectName(QStringLiteral("pupKiEdit"));
        pupKiEdit->setGeometry(QRect(127, 218, 90, 20));
        pupKiRecEdit = new QLineEdit(pupTab);
        pupKiRecEdit->setObjectName(QStringLiteral("pupKiRecEdit"));
        pupKiRecEdit->setGeometry(QRect(127, 248, 90, 20));
        pupStmEdit = new QLineEdit(pupTab);
        pupStmEdit->setObjectName(QStringLiteral("pupStmEdit"));
        pupStmEdit->setGeometry(QRect(127, 278, 90, 20));
        pupStmRecEdit = new QLineEdit(pupTab);
        pupStmRecEdit->setObjectName(QStringLiteral("pupStmRecEdit"));
        pupStmRecEdit->setGeometry(QRect(127, 308, 90, 20));
        pupEnStaErEdit = new QLineEdit(pupTab);
        pupEnStaErEdit->setObjectName(QStringLiteral("pupEnStaErEdit"));
        pupEnStaErEdit->setGeometry(QRect(127, 338, 90, 20));
        pupStaErEdit = new QLineEdit(pupTab);
        pupStaErEdit->setObjectName(QStringLiteral("pupStaErEdit"));
        pupStaErEdit->setGeometry(QRect(127, 368, 90, 20));
        pupF30Edit = new QLineEdit(pupTab);
        pupF30Edit->setObjectName(QStringLiteral("pupF30Edit"));
        pupF30Edit->setGeometry(QRect(127, 398, 90, 20));
        pupAtkEdit = new QLineEdit(pupTab);
        pupAtkEdit->setObjectName(QStringLiteral("pupAtkEdit"));
        pupAtkEdit->setGeometry(QRect(127, 428, 90, 20));
        label_59 = new QLabel(pupTab);
        label_59->setObjectName(QStringLiteral("label_59"));
        label_59->setGeometry(QRect(271, 70, 81, 16));
        label_60 = new QLabel(pupTab);
        label_60->setObjectName(QStringLiteral("label_60"));
        label_60->setGeometry(QRect(319, 100, 47, 13));
        label_61 = new QLabel(pupTab);
        label_61->setObjectName(QStringLiteral("label_61"));
        label_61->setGeometry(QRect(319, 130, 31, 16));
        label_62 = new QLabel(pupTab);
        label_62->setObjectName(QStringLiteral("label_62"));
        label_62->setGeometry(QRect(230, 160, 121, 16));
        label_63 = new QLabel(pupTab);
        label_63->setObjectName(QStringLiteral("label_63"));
        label_63->setGeometry(QRect(262, 190, 91, 16));
        label_64 = new QLabel(pupTab);
        label_64->setObjectName(QStringLiteral("label_64"));
        label_64->setGeometry(QRect(238, 220, 111, 16));
        label_65 = new QLabel(pupTab);
        label_65->setObjectName(QStringLiteral("label_65"));
        label_65->setGeometry(QRect(230, 250, 121, 16));
        label_66 = new QLabel(pupTab);
        label_66->setObjectName(QStringLiteral("label_66"));
        label_66->setGeometry(QRect(268, 280, 81, 16));
        label_67 = new QLabel(pupTab);
        label_67->setObjectName(QStringLiteral("label_67"));
        label_67->setGeometry(QRect(290, 310, 61, 16));
        label_68 = new QLabel(pupTab);
        label_68->setObjectName(QStringLiteral("label_68"));
        label_68->setGeometry(QRect(276, 340, 71, 16));
        label_69 = new QLabel(pupTab);
        label_69->setObjectName(QStringLiteral("label_69"));
        label_69->setGeometry(QRect(280, 370, 81, 16));
        label_70 = new QLabel(pupTab);
        label_70->setObjectName(QStringLiteral("label_70"));
        label_70->setGeometry(QRect(310, 400, 47, 13));
        label_71 = new QLabel(pupTab);
        label_71->setObjectName(QStringLiteral("label_71"));
        label_71->setGeometry(QRect(310, 430, 47, 13));
        pupBasicKiAtkEdit = new QLineEdit(pupTab);
        pupBasicKiAtkEdit->setObjectName(QStringLiteral("pupBasicKiAtkEdit"));
        pupBasicKiAtkEdit->setGeometry(QRect(350, 68, 90, 20));
        pupStrEdit = new QLineEdit(pupTab);
        pupStrEdit->setObjectName(QStringLiteral("pupStrEdit"));
        pupStrEdit->setGeometry(QRect(350, 98, 90, 20));
        pupBlaEdit = new QLineEdit(pupTab);
        pupBlaEdit->setObjectName(QStringLiteral("pupBlaEdit"));
        pupBlaEdit->setGeometry(QRect(350, 128, 90, 20));
        pupAtkDmgEdit = new QLineEdit(pupTab);
        pupAtkDmgEdit->setObjectName(QStringLiteral("pupAtkDmgEdit"));
        pupAtkDmgEdit->setGeometry(QRect(350, 158, 90, 20));
        pupKiDmgEdit = new QLineEdit(pupTab);
        pupKiDmgEdit->setObjectName(QStringLiteral("pupKiDmgEdit"));
        pupKiDmgEdit->setGeometry(QRect(350, 188, 90, 20));
        pupStrDmgEdit = new QLineEdit(pupTab);
        pupStrDmgEdit->setObjectName(QStringLiteral("pupStrDmgEdit"));
        pupStrDmgEdit->setGeometry(QRect(350, 218, 90, 20));
        pupBlaDmgEdit = new QLineEdit(pupTab);
        pupBlaDmgEdit->setObjectName(QStringLiteral("pupBlaDmgEdit"));
        pupBlaDmgEdit->setGeometry(QRect(350, 248, 90, 20));
        pupGroundSpeedEdit = new QLineEdit(pupTab);
        pupGroundSpeedEdit->setObjectName(QStringLiteral("pupGroundSpeedEdit"));
        pupGroundSpeedEdit->setGeometry(QRect(350, 278, 90, 20));
        pupAirSpeedEdit = new QLineEdit(pupTab);
        pupAirSpeedEdit->setObjectName(QStringLiteral("pupAirSpeedEdit"));
        pupAirSpeedEdit->setGeometry(QRect(350, 308, 90, 20));
        pupBoostSpeedEdit = new QLineEdit(pupTab);
        pupBoostSpeedEdit->setObjectName(QStringLiteral("pupBoostSpeedEdit"));
        pupBoostSpeedEdit->setGeometry(QRect(350, 338, 90, 20));
        pupDashSpeedEdit = new QLineEdit(pupTab);
        pupDashSpeedEdit->setObjectName(QStringLiteral("pupDashSpeedEdit"));
        pupDashSpeedEdit->setGeometry(QRect(350, 368, 90, 20));
        pupF64Edit = new QLineEdit(pupTab);
        pupF64Edit->setObjectName(QStringLiteral("pupF64Edit"));
        pupF64Edit->setGeometry(QRect(350, 398, 90, 20));
        pupF68Edit = new QLineEdit(pupTab);
        pupF68Edit->setObjectName(QStringLiteral("pupF68Edit"));
        pupF68Edit->setGeometry(QRect(350, 428, 90, 20));
        label_72 = new QLabel(pupTab);
        label_72->setObjectName(QStringLiteral("label_72"));
        label_72->setGeometry(QRect(460, 70, 47, 13));
        pupF6CEdit = new QLineEdit(pupTab);
        pupF6CEdit->setObjectName(QStringLiteral("pupF6CEdit"));
        pupF6CEdit->setGeometry(QRect(500, 68, 90, 20));
        label_73 = new QLabel(pupTab);
        label_73->setObjectName(QStringLiteral("label_73"));
        label_73->setGeometry(QRect(460, 100, 47, 13));
        label_74 = new QLabel(pupTab);
        label_74->setObjectName(QStringLiteral("label_74"));
        label_74->setGeometry(QRect(460, 130, 47, 13));
        label_75 = new QLabel(pupTab);
        label_75->setObjectName(QStringLiteral("label_75"));
        label_75->setGeometry(QRect(460, 160, 47, 13));
        label_76 = new QLabel(pupTab);
        label_76->setObjectName(QStringLiteral("label_76"));
        label_76->setGeometry(QRect(460, 190, 47, 13));
        label_77 = new QLabel(pupTab);
        label_77->setObjectName(QStringLiteral("label_77"));
        label_77->setGeometry(QRect(460, 220, 47, 13));
        label_78 = new QLabel(pupTab);
        label_78->setObjectName(QStringLiteral("label_78"));
        label_78->setGeometry(QRect(460, 250, 47, 13));
        label_79 = new QLabel(pupTab);
        label_79->setObjectName(QStringLiteral("label_79"));
        label_79->setGeometry(QRect(460, 280, 47, 13));
        label_80 = new QLabel(pupTab);
        label_80->setObjectName(QStringLiteral("label_80"));
        label_80->setGeometry(QRect(460, 310, 47, 13));
        label_81 = new QLabel(pupTab);
        label_81->setObjectName(QStringLiteral("label_81"));
        label_81->setGeometry(QRect(460, 340, 47, 13));
        label_82 = new QLabel(pupTab);
        label_82->setObjectName(QStringLiteral("label_82"));
        label_82->setGeometry(QRect(460, 370, 47, 13));
        pupF70Edit = new QLineEdit(pupTab);
        pupF70Edit->setObjectName(QStringLiteral("pupF70Edit"));
        pupF70Edit->setGeometry(QRect(500, 98, 90, 20));
        pupF74Edit = new QLineEdit(pupTab);
        pupF74Edit->setObjectName(QStringLiteral("pupF74Edit"));
        pupF74Edit->setGeometry(QRect(500, 128, 90, 20));
        pupF78Edit = new QLineEdit(pupTab);
        pupF78Edit->setObjectName(QStringLiteral("pupF78Edit"));
        pupF78Edit->setGeometry(QRect(500, 158, 90, 20));
        pupF7CEdit = new QLineEdit(pupTab);
        pupF7CEdit->setObjectName(QStringLiteral("pupF7CEdit"));
        pupF7CEdit->setGeometry(QRect(500, 188, 90, 20));
        pupF80Edit = new QLineEdit(pupTab);
        pupF80Edit->setObjectName(QStringLiteral("pupF80Edit"));
        pupF80Edit->setGeometry(QRect(500, 218, 90, 20));
        pupF84Edit = new QLineEdit(pupTab);
        pupF84Edit->setObjectName(QStringLiteral("pupF84Edit"));
        pupF84Edit->setGeometry(QRect(500, 248, 90, 20));
        pupF88Edit = new QLineEdit(pupTab);
        pupF88Edit->setObjectName(QStringLiteral("pupF88Edit"));
        pupF88Edit->setGeometry(QRect(500, 278, 90, 20));
        pupF8CEdit = new QLineEdit(pupTab);
        pupF8CEdit->setObjectName(QStringLiteral("pupF8CEdit"));
        pupF8CEdit->setGeometry(QRect(500, 308, 90, 20));
        pupF90Edit = new QLineEdit(pupTab);
        pupF90Edit->setObjectName(QStringLiteral("pupF90Edit"));
        pupF90Edit->setGeometry(QRect(500, 338, 90, 20));
        pupF94Edit = new QLineEdit(pupTab);
        pupF94Edit->setObjectName(QStringLiteral("pupF94Edit"));
        pupF94Edit->setGeometry(QRect(500, 368, 90, 20));
        pupAddButton = new QPushButton(pupTab);
        pupAddButton->setObjectName(QStringLiteral("pupAddButton"));
        pupAddButton->setGeometry(QRect(257, 20, 75, 23));
        pupRemoveButton = new QPushButton(pupTab);
        pupRemoveButton->setObjectName(QStringLiteral("pupRemoveButton"));
        pupRemoveButton->setGeometry(QRect(337, 20, 75, 23));
        pupComboBox = new QComboBox(pupTab);
        pupComboBox->setObjectName(QStringLiteral("pupComboBox"));
        pupComboBox->setGeometry(QRect(127, 20, 115, 22));
        tabWidget->addTab(pupTab, QString());
        auraTab = new QWidget();
        auraTab->setObjectName(QStringLiteral("auraTab"));
        auraTab->setAutoFillBackground(true);
        auraAddButton = new QPushButton(auraTab);
        auraAddButton->setObjectName(QStringLiteral("auraAddButton"));
        auraAddButton->setGeometry(QRect(257, 20, 75, 23));
        auraEnableCheck = new QCheckBox(auraTab);
        auraEnableCheck->setObjectName(QStringLiteral("auraEnableCheck"));
        auraEnableCheck->setGeometry(QRect(20, 23, 91, 17));
        auraComboBox = new QComboBox(auraTab);
        auraComboBox->setObjectName(QStringLiteral("auraComboBox"));
        auraComboBox->setGeometry(QRect(127, 20, 115, 22));
        auraRemoveButton = new QPushButton(auraTab);
        auraRemoveButton->setObjectName(QStringLiteral("auraRemoveButton"));
        auraRemoveButton->setGeometry(QRect(337, 20, 75, 23));
        label_85 = new QLabel(auraTab);
        label_85->setObjectName(QStringLiteral("label_85"));
        label_85->setGeometry(QRect(20, 70, 111, 16));
        label_86 = new QLabel(auraTab);
        label_86->setObjectName(QStringLiteral("label_86"));
        label_86->setGeometry(QRect(10, 360, 101, 16));
        auraCopyButton = new QToolButton(auraTab);
        auraCopyButton->setObjectName(QStringLiteral("auraCopyButton"));
        auraCopyButton->setGeometry(QRect(110, 67, 75, 23));
        auraCopyButton->setPopupMode(QToolButton::InstantPopup);
        auraCopyButton->setToolButtonStyle(Qt::ToolButtonTextOnly);
        auraPatchCopyButton = new QToolButton(auraTab);
        auraPatchCopyButton->setObjectName(QStringLiteral("auraPatchCopyButton"));
        auraPatchCopyButton->setGeometry(QRect(110, 357, 75, 23));
        auraPatchCopyButton->setPopupMode(QToolButton::InstantPopup);
        auraPatchCopyButton->setToolButtonStyle(Qt::ToolButtonTextOnly);
        label_87 = new QLabel(auraTab);
        label_87->setObjectName(QStringLiteral("label_87"));
        label_87->setGeometry(QRect(46, 110, 61, 16));
        auraIdEdit = new QLineEdit(auraTab);
        auraIdEdit->setObjectName(QStringLiteral("auraIdEdit"));
        auraIdEdit->setGeometry(QRect(110, 108, 90, 20));
        auraCustomCheck = new QCheckBox(auraTab);
        auraCustomCheck->setObjectName(QStringLiteral("auraCustomCheck"));
        auraCustomCheck->setGeometry(QRect(220, 110, 111, 17));
        label_88 = new QLabel(auraTab);
        label_88->setObjectName(QStringLiteral("label_88"));
        label_88->setGeometry(QRect(46, 150, 61, 16));
        auraEf0Edit = new QLineEdit(auraTab);
        auraEf0Edit->setObjectName(QStringLiteral("auraEf0Edit"));
        auraEf0Edit->setGeometry(QRect(110, 148, 90, 20));
        label_89 = new QLabel(auraTab);
        label_89->setObjectName(QStringLiteral("label_89"));
        label_89->setGeometry(QRect(52, 190, 51, 16));
        auraEf2Edit = new QLineEdit(auraTab);
        auraEf2Edit->setObjectName(QStringLiteral("auraEf2Edit"));
        auraEf2Edit->setGeometry(QRect(110, 188, 90, 20));
        label_90 = new QLabel(auraTab);
        label_90->setObjectName(QStringLiteral("label_90"));
        label_90->setGeometry(QRect(41, 230, 71, 16));
        auraEf4Edit = new QLineEdit(auraTab);
        auraEf4Edit->setObjectName(QStringLiteral("auraEf4Edit"));
        auraEf4Edit->setGeometry(QRect(110, 228, 90, 20));
        label_91 = new QLabel(auraTab);
        label_91->setObjectName(QStringLiteral("label_91"));
        label_91->setGeometry(QRect(40, 270, 71, 16));
        auraEf6Edit = new QLineEdit(auraTab);
        auraEf6Edit->setObjectName(QStringLiteral("auraEf6Edit"));
        auraEf6Edit->setGeometry(QRect(110, 268, 90, 20));
        label_92 = new QLabel(auraTab);
        label_92->setObjectName(QStringLiteral("label_92"));
        label_92->setGeometry(QRect(350, 150, 71, 16));
        auraEf1Edit = new QLineEdit(auraTab);
        auraEf1Edit->setObjectName(QStringLiteral("auraEf1Edit"));
        auraEf1Edit->setGeometry(QRect(413, 148, 90, 20));
        label_93 = new QLabel(auraTab);
        label_93->setObjectName(QStringLiteral("label_93"));
        label_93->setGeometry(QRect(350, 190, 71, 16));
        auraEf3Edit = new QLineEdit(auraTab);
        auraEf3Edit->setObjectName(QStringLiteral("auraEf3Edit"));
        auraEf3Edit->setGeometry(QRect(413, 188, 90, 20));
        label_94 = new QLabel(auraTab);
        label_94->setObjectName(QStringLiteral("label_94"));
        label_94->setGeometry(QRect(340, 230, 81, 16));
        auraEf5Edit = new QLineEdit(auraTab);
        auraEf5Edit->setObjectName(QStringLiteral("auraEf5Edit"));
        auraEf5Edit->setGeometry(QRect(413, 228, 90, 20));
        label_95 = new QLabel(auraTab);
        label_95->setObjectName(QStringLiteral("label_95"));
        label_95->setGeometry(QRect(30, 400, 81, 16));
        auraBH11Edit = new QLineEdit(auraTab);
        auraBH11Edit->setObjectName(QStringLiteral("auraBH11Edit"));
        auraBH11Edit->setGeometry(QRect(110, 398, 90, 20));
        label_96 = new QLabel(auraTab);
        label_96->setObjectName(QStringLiteral("label_96"));
        label_96->setGeometry(QRect(355, 400, 47, 13));
        auraInt2Edit = new QLineEdit(auraTab);
        auraInt2Edit->setObjectName(QStringLiteral("auraInt2Edit"));
        auraInt2Edit->setGeometry(QRect(413, 398, 90, 20));
        label_97 = new QLabel(auraTab);
        label_97->setObjectName(QStringLiteral("label_97"));
        label_97->setGeometry(QRect(46, 440, 81, 16));
        auraBH10Edit = new QLineEdit(auraTab);
        auraBH10Edit->setObjectName(QStringLiteral("auraBH10Edit"));
        auraBH10Edit->setGeometry(QRect(110, 438, 90, 20));
        auraInt3Edit = new QLineEdit(auraTab);
        auraInt3Edit->setObjectName(QStringLiteral("auraInt3Edit"));
        auraInt3Edit->setGeometry(QRect(413, 438, 90, 20));
        label_98 = new QLabel(auraTab);
        label_98->setObjectName(QStringLiteral("label_98"));
        label_98->setGeometry(QRect(355, 440, 47, 13));
        auraTeleportCheck = new QCheckBox(auraTab);
        auraTeleportCheck->setObjectName(QStringLiteral("auraTeleportCheck"));
        auraTeleportCheck->setGeometry(QRect(35, 480, 121, 17));
        label_99 = new QLabel(auraTab);
        label_99->setObjectName(QStringLiteral("label_99"));
        label_99->setGeometry(QRect(296, 480, 121, 16));
        auraBH13Edit = new QLineEdit(auraTab);
        auraBH13Edit->setObjectName(QStringLiteral("auraBH13Edit"));
        auraBH13Edit->setGeometry(QRect(413, 478, 90, 20));
        label_29 = new QLabel(auraTab);
        label_29->setObjectName(QStringLiteral("label_29"));
        label_29->setGeometry(QRect(44, 520, 81, 13));
        auraBH66Edit = new QLineEdit(auraTab);
        auraBH66Edit->setObjectName(QStringLiteral("auraBH66Edit"));
        auraBH66Edit->setGeometry(QRect(110, 518, 90, 20));
        label_102 = new QLabel(auraTab);
        label_102->setObjectName(QStringLiteral("label_102"));
        label_102->setGeometry(QRect(35, 600, 81, 16));
        auraHairColorEdit = new QLineEdit(auraTab);
        auraHairColorEdit->setObjectName(QStringLiteral("auraHairColorEdit"));
        auraHairColorEdit->setGeometry(QRect(110, 598, 90, 20));
        auraGetHairColorButton = new QToolButton(auraTab);
        auraGetHairColorButton->setObjectName(QStringLiteral("auraGetHairColorButton"));
        auraGetHairColorButton->setGeometry(QRect(212, 597, 75, 23));
        auraGetHairColorButton->setPopupMode(QToolButton::InstantPopup);
        auraGetHairColorButton->setToolButtonStyle(Qt::ToolButtonTextOnly);
        label_103 = new QLabel(auraTab);
        label_103->setObjectName(QStringLiteral("label_103"));
        label_103->setGeometry(QRect(282, 520, 141, 16));
        auraRemoveHairAccCombo = new QComboBox(auraTab);
        auraRemoveHairAccCombo->setObjectName(QStringLiteral("auraRemoveHairAccCombo"));
        auraRemoveHairAccCombo->setGeometry(QRect(413, 518, 151, 22));
        label_104 = new QLabel(auraTab);
        label_104->setObjectName(QStringLiteral("label_104"));
        label_104->setGeometry(QRect(331, 600, 91, 16));
        auraEyesColorEdit = new QLineEdit(auraTab);
        auraEyesColorEdit->setObjectName(QStringLiteral("auraEyesColorEdit"));
        auraEyesColorEdit->setGeometry(QRect(413, 598, 90, 20));
        auraGetEyesColorButton = new QToolButton(auraTab);
        auraGetEyesColorButton->setObjectName(QStringLiteral("auraGetEyesColorButton"));
        auraGetEyesColorButton->setGeometry(QRect(515, 597, 75, 23));
        auraGetEyesColorButton->setPopupMode(QToolButton::InstantPopup);
        auraGetEyesColorButton->setToolButtonStyle(Qt::ToolButtonTextOnly);
        auraMoreColorsEdit = new QLineEdit(auraTab);
        auraMoreColorsEdit->setObjectName(QStringLiteral("auraMoreColorsEdit"));
        auraMoreColorsEdit->setGeometry(QRect(100, 638, 403, 22));
        label_109 = new QLabel(auraTab);
        label_109->setObjectName(QStringLiteral("label_109"));
        label_109->setGeometry(QRect(10, 640, 91, 16));
        auraAddMoreColorButton = new QToolButton(auraTab);
        auraAddMoreColorButton->setObjectName(QStringLiteral("auraAddMoreColorButton"));
        auraAddMoreColorButton->setGeometry(QRect(515, 637, 75, 23));
        auraAddMoreColorButton->setPopupMode(QToolButton::InstantPopup);
        auraAddMoreColorButton->setToolButtonStyle(Qt::ToolButtonTextOnly);
        auraBpeEdit = new QLineEdit(auraTab);
        auraBpeEdit->setObjectName(QStringLiteral("auraBpeEdit"));
        auraBpeEdit->setGeometry(QRect(413, 268, 90, 20));
        label_110 = new QLabel(auraTab);
        label_110->setObjectName(QStringLiteral("label_110"));
        label_110->setGeometry(QRect(370, 270, 41, 16));
        auraBpeFlag1Check = new QCheckBox(auraTab);
        auraBpeFlag1Check->setObjectName(QStringLiteral("auraBpeFlag1Check"));
        auraBpeFlag1Check->setGeometry(QRect(110, 310, 81, 20));
        auraBpeFlag2Check = new QCheckBox(auraTab);
        auraBpeFlag2Check->setObjectName(QStringLiteral("auraBpeFlag2Check"));
        auraBpeFlag2Check->setGeometry(QRect(413, 310, 81, 20));
        aurBpeButton = new QToolButton(auraTab);
        aurBpeButton->setObjectName(QStringLiteral("aurBpeButton"));
        aurBpeButton->setGeometry(QRect(510, 267, 75, 23));
        aurBpeButton->setPopupMode(QToolButton::InstantPopup);
        aurBpeButton->setToolButtonStyle(Qt::ToolButtonTextOnly);
        auraBH64Edit = new QLineEdit(auraTab);
        auraBH64Edit->setObjectName(QStringLiteral("auraBH64Edit"));
        auraBH64Edit->setGeometry(QRect(110, 558, 90, 20));
        label_111 = new QLabel(auraTab);
        label_111->setObjectName(QStringLiteral("label_111"));
        label_111->setGeometry(QRect(5, 560, 111, 16));
        label_112 = new QLabel(auraTab);
        label_112->setObjectName(QStringLiteral("label_112"));
        label_112->setGeometry(QRect(10, 680, 501, 16));
        tabWidget->addTab(auraTab, QString());
        bcsTab = new QWidget();
        bcsTab->setObjectName(QStringLiteral("bcsTab"));
        bcsTab->setAutoFillBackground(true);
        label_100 = new QLabel(bcsTab);
        label_100->setObjectName(QStringLiteral("label_100"));
        label_100->setGeometry(QRect(20, 30, 571, 16));
        label_101 = new QLabel(bcsTab);
        label_101->setObjectName(QStringLiteral("label_101"));
        label_101->setGeometry(QRect(20, 70, 111, 16));
        bcsAttachmentEdit = new QLineEdit(bcsTab);
        bcsAttachmentEdit->setObjectName(QStringLiteral("bcsAttachmentEdit"));
        bcsAttachmentEdit->setEnabled(false);
        bcsAttachmentEdit->setGeometry(QRect(95, 69, 355, 20));
        bcsAttachmentSetButton = new QPushButton(bcsTab);
        bcsAttachmentSetButton->setObjectName(QStringLiteral("bcsAttachmentSetButton"));
        bcsAttachmentSetButton->setGeometry(QRect(459, 68, 61, 23));
        bcsAttachmentRemoveButton = new QPushButton(bcsTab);
        bcsAttachmentRemoveButton->setObjectName(QStringLiteral("bcsAttachmentRemoveButton"));
        bcsAttachmentRemoveButton->setGeometry(QRect(527, 68, 75, 23));
        bcsBodyCheck = new QCheckBox(bcsTab);
        bcsBodyCheck->setObjectName(QStringLiteral("bcsBodyCheck"));
        bcsBodyCheck->setGeometry(QRect(20, 140, 151, 17));
        bcsBodyRemoveButton = new QPushButton(bcsTab);
        bcsBodyRemoveButton->setObjectName(QStringLiteral("bcsBodyRemoveButton"));
        bcsBodyRemoveButton->setGeometry(QRect(527, 137, 75, 23));
        bcsBodyAddButton = new QPushButton(bcsTab);
        bcsBodyAddButton->setObjectName(QStringLiteral("bcsBodyAddButton"));
        bcsBodyAddButton->setGeometry(QRect(447, 137, 75, 23));
        bcsBodyComboBox = new QComboBox(bcsTab);
        bcsBodyComboBox->setObjectName(QStringLiteral("bcsBodyComboBox"));
        bcsBodyComboBox->setGeometry(QRect(317, 137, 115, 22));
        bcsBodyId = new QLabel(bcsTab);
        bcsBodyId->setObjectName(QStringLiteral("bcsBodyId"));
        bcsBodyId->setGeometry(QRect(20, 190, 191, 16));
        label_105 = new QLabel(bcsTab);
        label_105->setObjectName(QStringLiteral("label_105"));
        label_105->setGeometry(QRect(390, 190, 47, 13));
        bcsBodyRaceComboBox = new QComboBox(bcsTab);
        bcsBodyRaceComboBox->setObjectName(QStringLiteral("bcsBodyRaceComboBox"));
        bcsBodyRaceComboBox->setGeometry(QRect(450, 187, 91, 22));
        bcsBodyEdit = new QTextEdit(bcsTab);
        bcsBodyEdit->setObjectName(QStringLiteral("bcsBodyEdit"));
        bcsBodyEdit->setGeometry(QRect(30, 240, 555, 281));
        bcsBodyEdit->setAcceptRichText(false);
        tabWidget->addTab(bcsTab, QString());
        MainWindow->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 661, 22));
        menuFile = new QMenu(menuBar);
        menuFile->setObjectName(QStringLiteral("menuFile"));
        menuHelp = new QMenu(menuBar);
        menuHelp->setObjectName(QStringLiteral("menuHelp"));
        menuTools = new QMenu(menuBar);
        menuTools->setObjectName(QStringLiteral("menuTools"));
        MainWindow->setMenuBar(menuBar);
        mainToolBar = new QToolBar(MainWindow);
        mainToolBar->setObjectName(QStringLiteral("mainToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        MainWindow->setStatusBar(statusBar);

        menuBar->addAction(menuFile->menuAction());
        menuBar->addAction(menuTools->menuAction());
        menuBar->addAction(menuHelp->menuAction());
        menuFile->addAction(actionOpen);
        menuFile->addAction(actionSave);
        menuFile->addSeparator();
        menuFile->addAction(actionExit);
        menuHelp->addAction(actionAbout);
        menuTools->addAction(actionImportSkillDir);
        mainToolBar->addAction(actionOpen);
        mainToolBar->addAction(actionSave);

        retranslateUi(MainWindow);

        tabWidget->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "XV2 Skill Creator", 0));
        actionOpen->setText(QApplication::translate("MainWindow", "Open", 0));
        actionSave->setText(QApplication::translate("MainWindow", "Save as...", 0));
        actionExit->setText(QApplication::translate("MainWindow", "Exit", 0));
        actionAbout->setText(QApplication::translate("MainWindow", "About", 0));
        actionFromGameCus->setText(QApplication::translate("MainWindow", "From game", 0));
#ifndef QT_NO_TOOLTIP
        actionFromGameCus->setToolTip(QApplication::translate("MainWindow", "From game", 0));
#endif // QT_NO_TOOLTIP
        actionFromExternalCus->setText(QApplication::translate("MainWindow", "From external CUS", 0));
#ifndef QT_NO_TOOLTIP
        actionFromExternalCus->setToolTip(QApplication::translate("MainWindow", "From external CUS", 0));
#endif // QT_NO_TOOLTIP
        actionImportSkillDir->setText(QApplication::translate("MainWindow", "Import skill directory", 0));
        actionFromGameIdb->setText(QApplication::translate("MainWindow", "From game", 0));
#ifndef QT_NO_TOOLTIP
        actionFromGameIdb->setToolTip(QApplication::translate("MainWindow", "From game", 0));
#endif // QT_NO_TOOLTIP
        actionFromGamePup->setText(QApplication::translate("MainWindow", "From game", 0));
#ifndef QT_NO_TOOLTIP
        actionFromGamePup->setToolTip(QApplication::translate("MainWindow", "From game", 0));
#endif // QT_NO_TOOLTIP
        actionFromExternalPup->setText(QApplication::translate("MainWindow", "From external PUP", 0));
#ifndef QT_NO_TOOLTIP
        actionFromExternalPup->setToolTip(QApplication::translate("MainWindow", "From external PUP", 0));
#endif // QT_NO_TOOLTIP
        actionFromPupSkillUsage->setText(QApplication::translate("MainWindow", "From skill usage", 0));
#ifndef QT_NO_TOOLTIP
        actionFromPupSkillUsage->setToolTip(QApplication::translate("MainWindow", "From skill usage", 0));
#endif // QT_NO_TOOLTIP
        actionFromGameAur->setText(QApplication::translate("MainWindow", "From game", 0));
#ifndef QT_NO_TOOLTIP
        actionFromGameAur->setToolTip(QApplication::translate("MainWindow", "From game", 0));
#endif // QT_NO_TOOLTIP
        actionFromExternalAur->setText(QApplication::translate("MainWindow", "From external AUR", 0));
#ifndef QT_NO_TOOLTIP
        actionFromExternalAur->setToolTip(QApplication::translate("MainWindow", "From external AUR", 0));
#endif // QT_NO_TOOLTIP
        actionFromAuraSkillUsage->setText(QApplication::translate("MainWindow", "From skill usage", 0));
#ifndef QT_NO_TOOLTIP
        actionFromAuraSkillUsage->setToolTip(QApplication::translate("MainWindow", "From skill usage", 0));
#endif // QT_NO_TOOLTIP
        actionFromAuraCharUsage->setText(QApplication::translate("MainWindow", "From char usage", 0));
#ifndef QT_NO_TOOLTIP
        actionFromAuraCharUsage->setToolTip(QApplication::translate("MainWindow", "From char usage", 0));
#endif // QT_NO_TOOLTIP
        actionFromAuraPatchSkillUsage->setText(QApplication::translate("MainWindow", "From skill usage", 0));
#ifndef QT_NO_TOOLTIP
        actionFromAuraPatchSkillUsage->setToolTip(QApplication::translate("MainWindow", "From skill usage", 0));
#endif // QT_NO_TOOLTIP
        actionFromHumBcs->setText(QApplication::translate("MainWindow", "From HUM.bcs", 0));
        actionFromHufBcs->setText(QApplication::translate("MainWindow", "From HUF.bcs", 0));
        actionFromBcsFile->setText(QApplication::translate("MainWindow", "From bcs file", 0));
        actionFromHumBcsEyes->setText(QApplication::translate("MainWindow", "From HUM.bcs", 0));
        actionFromHufBcsEyes->setText(QApplication::translate("MainWindow", "From HUF.bcs", 0));
        actionFromNmcBcsEyes->setText(QApplication::translate("MainWindow", "From NMC.bcs", 0));
#ifndef QT_NO_TOOLTIP
        actionFromNmcBcsEyes->setToolTip(QApplication::translate("MainWindow", "From NMC.bcs", 0));
#endif // QT_NO_TOOLTIP
        actionFromFriBcsEyes->setText(QApplication::translate("MainWindow", "From FRI.bcs", 0));
#ifndef QT_NO_TOOLTIP
        actionFromFriBcsEyes->setToolTip(QApplication::translate("MainWindow", "From FRI.bcs", 0));
#endif // QT_NO_TOOLTIP
        actionFromMamBcsEyes->setText(QApplication::translate("MainWindow", "From MAM.bcs", 0));
#ifndef QT_NO_TOOLTIP
        actionFromMamBcsEyes->setToolTip(QApplication::translate("MainWindow", "From MAM.bcs", 0));
#endif // QT_NO_TOOLTIP
        actionFromMafBcsEyes->setText(QApplication::translate("MainWindow", "From MAF.bcs", 0));
#ifndef QT_NO_TOOLTIP
        actionFromMafBcsEyes->setToolTip(QApplication::translate("MainWindow", "From MAF.bcs", 0));
#endif // QT_NO_TOOLTIP
        actionFromBcsFileEyes->setText(QApplication::translate("MainWindow", "From bcs file", 0));
        actionFromHumBcsMore->setText(QApplication::translate("MainWindow", "From HUM.bcs", 0));
        actionFromHufBcsMore->setText(QApplication::translate("MainWindow", "From HUF.bcs", 0));
        actionFromNmcBcsMore->setText(QApplication::translate("MainWindow", "From NMC.bcs", 0));
#ifndef QT_NO_TOOLTIP
        actionFromNmcBcsMore->setToolTip(QApplication::translate("MainWindow", "From NMC.bcs", 0));
#endif // QT_NO_TOOLTIP
        actionFromFriBcsMore->setText(QApplication::translate("MainWindow", "From FRI.bcs", 0));
#ifndef QT_NO_TOOLTIP
        actionFromFriBcsMore->setToolTip(QApplication::translate("MainWindow", "From FRI.bcs", 0));
#endif // QT_NO_TOOLTIP
        actionFromMamBcsMore->setText(QApplication::translate("MainWindow", "From MAM.bcs", 0));
#ifndef QT_NO_TOOLTIP
        actionFromMamBcsMore->setToolTip(QApplication::translate("MainWindow", "From MAM.bcs", 0));
#endif // QT_NO_TOOLTIP
        actionFromMafBcsMore->setText(QApplication::translate("MainWindow", "From MAF.bcs", 0));
#ifndef QT_NO_TOOLTIP
        actionFromMafBcsMore->setToolTip(QApplication::translate("MainWindow", "From MAF.bcs", 0));
#endif // QT_NO_TOOLTIP
        actionFromBcsFileMore->setText(QApplication::translate("MainWindow", "From bcs file", 0));
        actionFromCmnBpe->setText(QApplication::translate("MainWindow", "From cmn.bpe", 0));
        actionFromCmnBpeBO->setText(QApplication::translate("MainWindow", "From cmn.bpe (only BodyOutline)", 0));
        label_2->setText(QApplication::translate("MainWindow", "Version:", 0));
        guidButton->setText(QApplication::translate("MainWindow", "Generate new", 0));
        label->setText(QApplication::translate("MainWindow", "Name:", 0));
        label_5->setText(QApplication::translate("MainWindow", "Skill name:", 0));
        label_4->setText(QApplication::translate("MainWindow", "GUID:", 0));
        skillNameLangComboBox->clear();
        skillNameLangComboBox->insertItems(0, QStringList()
         << QApplication::translate("MainWindow", "English", 0)
         << QApplication::translate("MainWindow", "Spanish (es)", 0)
         << QApplication::translate("MainWindow", "Spanish (ca)", 0)
         << QApplication::translate("MainWindow", "French", 0)
         << QApplication::translate("MainWindow", "German", 0)
         << QApplication::translate("MainWindow", "Italian", 0)
         << QApplication::translate("MainWindow", "Portuguese", 0)
         << QApplication::translate("MainWindow", "Polish", 0)
         << QApplication::translate("MainWindow", "Russian", 0)
         << QApplication::translate("MainWindow", "Chinese (tw)", 0)
         << QApplication::translate("MainWindow", "Chinese (zh)", 0)
         << QApplication::translate("MainWindow", "Korean", 0)
        );
        label_3->setText(QApplication::translate("MainWindow", "Author:", 0));
        skillNameCopyButton->setText(QApplication::translate("MainWindow", "Copy from game", 0));
        label_6->setText(QApplication::translate("MainWindow", "Skill type:", 0));
        skillTypeComboBox->clear();
        skillTypeComboBox->insertItems(0, QStringList()
         << QApplication::translate("MainWindow", "Super", 0)
         << QApplication::translate("MainWindow", "Ultimate", 0)
         << QApplication::translate("MainWindow", "Evasive", 0)
         << QApplication::translate("MainWindow", "Awaken", 0)
         << QApplication::translate("MainWindow", "Blast", 0)
        );
        label_32->setText(QApplication::translate("MainWindow", "Desc.:", 0));
        skillDescLangComboBox->clear();
        skillDescLangComboBox->insertItems(0, QStringList()
         << QApplication::translate("MainWindow", "English", 0)
         << QApplication::translate("MainWindow", "Spanish (es)", 0)
         << QApplication::translate("MainWindow", "Spanish (ca)", 0)
         << QApplication::translate("MainWindow", "French", 0)
         << QApplication::translate("MainWindow", "German", 0)
         << QApplication::translate("MainWindow", "Italian", 0)
         << QApplication::translate("MainWindow", "Portuguese", 0)
         << QApplication::translate("MainWindow", "Polish", 0)
         << QApplication::translate("MainWindow", "Russian", 0)
         << QApplication::translate("MainWindow", "Chinese (tw)", 0)
         << QApplication::translate("MainWindow", "Chinese (zh)", 0)
         << QApplication::translate("MainWindow", "Korean", 0)
        );
        skillDescCopyButton->setText(QApplication::translate("MainWindow", "Copy from game", 0));
        label_83->setText(QApplication::translate("MainWindow", "Transformation names", 0));
        label_84->setText(QApplication::translate("MainWindow", "Name:", 0));
        skillTransLangComboBox->clear();
        skillTransLangComboBox->insertItems(0, QStringList()
         << QApplication::translate("MainWindow", "English", 0)
         << QApplication::translate("MainWindow", "Spanish (es)", 0)
         << QApplication::translate("MainWindow", "Spanish (ca)", 0)
         << QApplication::translate("MainWindow", "French", 0)
         << QApplication::translate("MainWindow", "German", 0)
         << QApplication::translate("MainWindow", "Italian", 0)
         << QApplication::translate("MainWindow", "Portuguese", 0)
         << QApplication::translate("MainWindow", "Polish", 0)
         << QApplication::translate("MainWindow", "Russian", 0)
         << QApplication::translate("MainWindow", "Chinese (tw)", 0)
         << QApplication::translate("MainWindow", "Chinese (zh)", 0)
         << QApplication::translate("MainWindow", "Korean", 0)
        );
        skillTransCopyButton->setText(QApplication::translate("MainWindow", "Copy from game", 0));
        skillTransAddButton->setText(QApplication::translate("MainWindow", "Add", 0));
        skillTransRemoveButton->setText(QApplication::translate("MainWindow", "Remove", 0));
        guidCopyButton->setText(QApplication::translate("MainWindow", "Copy to clipboard", 0));
        label_113->setText(QApplication::translate("MainWindow", "How:", 0));
        skillHowLangComboBox->clear();
        skillHowLangComboBox->insertItems(0, QStringList()
         << QApplication::translate("MainWindow", "English", 0)
         << QApplication::translate("MainWindow", "Spanish (es)", 0)
         << QApplication::translate("MainWindow", "Spanish (ca)", 0)
         << QApplication::translate("MainWindow", "French", 0)
         << QApplication::translate("MainWindow", "German", 0)
         << QApplication::translate("MainWindow", "Italian", 0)
         << QApplication::translate("MainWindow", "Portuguese", 0)
         << QApplication::translate("MainWindow", "Polish", 0)
         << QApplication::translate("MainWindow", "Russian", 0)
         << QApplication::translate("MainWindow", "Chinese (tw)", 0)
         << QApplication::translate("MainWindow", "Chinese (zh)", 0)
         << QApplication::translate("MainWindow", "Korean", 0)
        );
        skillHowCopyButton->setText(QApplication::translate("MainWindow", "Copy from game", 0));
        tabWidget->setTabText(tabWidget->indexOf(modInfoTab), QApplication::translate("MainWindow", "Mod info", 0));
        label_7->setText(QApplication::translate("MainWindow", "Skill files:", 0));
        label_8->setText(QApplication::translate("MainWindow", "Additional data*:", 0));
        label_9->setText(QApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">*This directory is optional. Use with care and only when needed!</span></p></body></html>", 0));
        addEditButton->setText(QApplication::translate("MainWindow", "Change", 0));
        skillFilesButton->setText(QApplication::translate("MainWindow", "Change", 0));
        tabWidget->setTabText(tabWidget->indexOf(filesTab), QApplication::translate("MainWindow", "Files", 0));
        label_10->setText(QApplication::translate("MainWindow", "Name:", 0));
        label_11->setText(QApplication::translate("MainWindow", "Race lock:", 0));
        cusHumCheck->setText(QApplication::translate("MainWindow", "HUM", 0));
        cusHufCheck->setText(QApplication::translate("MainWindow", "HUF", 0));
        cusSymCheck->setText(QApplication::translate("MainWindow", "SYM", 0));
        cusSyfCheck->setText(QApplication::translate("MainWindow", "SYF", 0));
        cusNmcCheck->setText(QApplication::translate("MainWindow", "NMC", 0));
        cusFriCheck->setText(QApplication::translate("MainWindow", "FRI", 0));
        cusMamCheck->setText(QApplication::translate("MainWindow", "MAM", 0));
        cusMafCheck->setText(QApplication::translate("MainWindow", "MAF", 0));
        label_12->setText(QApplication::translate("MainWindow", "Type:", 0));
        label_13->setText(QApplication::translate("MainWindow", "U_0E / 2?:", 0));
        label_14->setText(QApplication::translate("MainWindow", "Partset:", 0));
        label_15->setText(QApplication::translate("MainWindow", "U_12 / 3?:", 0));
        label_16->setText(QApplication::translate("MainWindow", "ean:", 0));
        label_17->setText(QApplication::translate("MainWindow", "cam.ean:", 0));
        label_18->setText(QApplication::translate("MainWindow", "eepk:", 0));
        label_21->setText(QApplication::translate("MainWindow", "bac:", 0));
        label_22->setText(QApplication::translate("MainWindow", "bcm:", 0));
        label_23->setText(QApplication::translate("MainWindow", "U_30:", 0));
        label_24->setText(QApplication::translate("MainWindow", "U_32 / 11?:", 0));
        label_25->setText(QApplication::translate("MainWindow", "U_34 / 12?:", 0));
        label_26->setText(QApplication::translate("MainWindow", "Skill type:", 0));
        label_27->setText(QApplication::translate("MainWindow", "PUP:", 0));
        label_28->setText(QApplication::translate("MainWindow", "Aura / trans control:", 0));
        label_30->setText(QApplication::translate("MainWindow", "Change skillset:", 0));
        label_31->setText(QApplication::translate("MainWindow", "Num of transforms:", 0));
        cusCopyButton->setText(QApplication::translate("MainWindow", "Copy", 0));
        cusAcbSeButton->setText(QApplication::translate("MainWindow", "acb (SE):", 0));
        cusAcbVoxButton->setText(QApplication::translate("MainWindow", "acb (VOX):", 0));
        cusModelButton->setText(QApplication::translate("MainWindow", "Model:", 0));
        label_107->setText(QApplication::translate("MainWindow", "U_44:", 0));
        label_108->setText(QApplication::translate("MainWindow", "U_48:", 0));
        tabWidget->setTabText(tabWidget->indexOf(cusTab), QApplication::translate("MainWindow", "CUS", 0));
        label_20->setText(QApplication::translate("MainWindow", "Stars:", 0));
        idbHumCheck->setText(QApplication::translate("MainWindow", "HUM", 0));
        idbNmcCheck->setText(QApplication::translate("MainWindow", "NMC", 0));
        idbSymCheck->setText(QApplication::translate("MainWindow", "SYM", 0));
        idbHufCheck->setText(QApplication::translate("MainWindow", "HUF", 0));
        label_19->setText(QApplication::translate("MainWindow", "Race lock:", 0));
        idbMamCheck->setText(QApplication::translate("MainWindow", "MAM", 0));
        idbMafCheck->setText(QApplication::translate("MainWindow", "MAF", 0));
        idbFriCheck->setText(QApplication::translate("MainWindow", "FRI", 0));
        idbSyfCheck->setText(QApplication::translate("MainWindow", "SYF", 0));
        label_33->setText(QApplication::translate("MainWindow", "U_0A:", 0));
        idbCopyButton->setText(QApplication::translate("MainWindow", "Copy", 0));
        label_34->setText(QApplication::translate("MainWindow", "Story Progress Flags:", 0));
        label_35->setText(QApplication::translate("MainWindow", "U_0E:", 0));
        label_36->setText(QApplication::translate("MainWindow", "Buy:", 0));
        label_37->setText(QApplication::translate("MainWindow", "Sell:", 0));
        label_38->setText(QApplication::translate("MainWindow", "TP:", 0));
        label_39->setText(QApplication::translate("MainWindow", "Model:", 0));
        label_40->setText(QApplication::translate("MainWindow", "U_24:", 0));
        label_41->setText(QApplication::translate("MainWindow", "U_28:", 0));
        label_42->setText(QApplication::translate("MainWindow", "U_2C:", 0));
        label_43->setText(QApplication::translate("MainWindow", "Effect 1:", 0));
        idbEff1Button->setText(QApplication::translate("MainWindow", "Edit", 0));
        idbEff2Button->setText(QApplication::translate("MainWindow", "Edit", 0));
        idbEff3Button->setText(QApplication::translate("MainWindow", "Edit", 0));
        label_44->setText(QApplication::translate("MainWindow", "Effect 2:", 0));
        label_45->setText(QApplication::translate("MainWindow", "Effect 3:", 0));
        idbEnableCheck->setText(QApplication::translate("MainWindow", "Enable IDB", 0));
        label_106->setText(QApplication::translate("MainWindow", "NU_0C:", 0));
        tabWidget->setTabText(tabWidget->indexOf(idbTab), QApplication::translate("MainWindow", "IDB", 0));
        pupEnableCheck->setText(QApplication::translate("MainWindow", "Enable PUP", 0));
        pupCopyButton->setText(QApplication::translate("MainWindow", "Copy", 0));
        label_46->setText(QApplication::translate("MainWindow", "U_04:", 0));
        label_47->setText(QApplication::translate("MainWindow", "Super Soul 1:", 0));
        label_48->setText(QApplication::translate("MainWindow", "Super Soul 2:", 0));
        label_49->setText(QApplication::translate("MainWindow", "HEA:", 0));
        label_50->setText(QApplication::translate("MainWindow", "F_14:", 0));
        label_51->setText(QApplication::translate("MainWindow", "KI:", 0));
        label_52->setText(QApplication::translate("MainWindow", "Ki recovery:", 0));
        label_53->setText(QApplication::translate("MainWindow", "STM:", 0));
        label_54->setText(QApplication::translate("MainWindow", "Stamina recovery:", 0));
        label_55->setText(QApplication::translate("MainWindow", "Enemy stamina eraser:", 0));
        label_56->setText(QApplication::translate("MainWindow", "Stamina eraser:", 0));
        label_57->setText(QApplication::translate("MainWindow", "F_30:", 0));
        label_58->setText(QApplication::translate("MainWindow", "ATK:", 0));
        label_59->setText(QApplication::translate("MainWindow", "Basic ki attack:", 0));
        label_60->setText(QApplication::translate("MainWindow", "STR:", 0));
        label_61->setText(QApplication::translate("MainWindow", "BLA:", 0));
        label_62->setText(QApplication::translate("MainWindow", "Normal attack damage:", 0));
        label_63->setText(QApplication::translate("MainWindow", "Ki blast damage:", 0));
        label_64->setText(QApplication::translate("MainWindow", "Super strike damage:", 0));
        label_65->setText(QApplication::translate("MainWindow", "Super Ki Blast damage:", 0));
        label_66->setText(QApplication::translate("MainWindow", "Ground speed:", 0));
        label_67->setText(QApplication::translate("MainWindow", "Air speed:", 0));
        label_68->setText(QApplication::translate("MainWindow", "Boost speed:", 0));
        label_69->setText(QApplication::translate("MainWindow", "Dash speed:", 0));
        label_70->setText(QApplication::translate("MainWindow", "F_64:", 0));
        label_71->setText(QApplication::translate("MainWindow", "F_68:", 0));
        label_72->setText(QApplication::translate("MainWindow", "F_6C:", 0));
        label_73->setText(QApplication::translate("MainWindow", "F_70:", 0));
        label_74->setText(QApplication::translate("MainWindow", "F_74:", 0));
        label_75->setText(QApplication::translate("MainWindow", "F_78:", 0));
        label_76->setText(QApplication::translate("MainWindow", "F_7C:", 0));
        label_77->setText(QApplication::translate("MainWindow", "F_80:", 0));
        label_78->setText(QApplication::translate("MainWindow", "F_84:", 0));
        label_79->setText(QApplication::translate("MainWindow", "F_88:", 0));
        label_80->setText(QApplication::translate("MainWindow", "F_8C:", 0));
        label_81->setText(QApplication::translate("MainWindow", "F_90:", 0));
        label_82->setText(QApplication::translate("MainWindow", "F_94:", 0));
        pupAddButton->setText(QApplication::translate("MainWindow", "Add", 0));
        pupRemoveButton->setText(QApplication::translate("MainWindow", "Remove", 0));
        tabWidget->setTabText(tabWidget->indexOf(pupTab), QApplication::translate("MainWindow", "PUP", 0));
        auraAddButton->setText(QApplication::translate("MainWindow", "Add", 0));
        auraEnableCheck->setText(QApplication::translate("MainWindow", "Enable", 0));
        auraRemoveButton->setText(QApplication::translate("MainWindow", "Remove", 0));
        label_85->setText(QApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Aura section </span></p></body></html>", 0));
        label_86->setText(QApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Patcher section</span></p></body></html>", 0));
        auraCopyButton->setText(QApplication::translate("MainWindow", "Copy", 0));
        auraPatchCopyButton->setText(QApplication::translate("MainWindow", "Copy", 0));
        label_87->setText(QApplication::translate("MainWindow", "Real aur id:", 0));
        auraCustomCheck->setText(QApplication::translate("MainWindow", "Use custom aura", 0));
        label_88->setText(QApplication::translate("MainWindow", "BoostStart:", 0));
        label_89->setText(QApplication::translate("MainWindow", "BoostEnd:", 0));
        label_90->setText(QApplication::translate("MainWindow", "KiryokuMax:", 0));
        label_91->setText(QApplication::translate("MainWindow", "HenshinEnd:", 0));
        label_92->setText(QApplication::translate("MainWindow", "BoostLoop:", 0));
        label_93->setText(QApplication::translate("MainWindow", "KiaiCharge:", 0));
        label_94->setText(QApplication::translate("MainWindow", "HenshinStart:", 0));
        label_95->setText(QApplication::translate("MainWindow", "BH11 (Stance):", 0));
        label_96->setText(QApplication::translate("MainWindow", "Integer 2:", 0));
        label_97->setText(QApplication::translate("MainWindow", "BH10 (dyt):", 0));
        label_98->setText(QApplication::translate("MainWindow", "Integer 3:", 0));
        auraTeleportCheck->setText(QApplication::translate("MainWindow", "Force teleport", 0));
        label_99->setText(QApplication::translate("MainWindow", "BH13 (Portrait Switch):", 0));
        label_29->setText(QApplication::translate("MainWindow", "BH66 (bcm):", 0));
        label_102->setText(QApplication::translate("MainWindow", "Bcs hair color:", 0));
        auraGetHairColorButton->setText(QApplication::translate("MainWindow", "Get from", 0));
        label_103->setText(QApplication::translate("MainWindow", "Remove hair accessories:", 0));
        auraRemoveHairAccCombo->clear();
        auraRemoveHairAccCombo->insertItems(0, QStringList()
         << QApplication::translate("MainWindow", "Default game behaviour", 0)
         << QApplication::translate("MainWindow", "Don't remove", 0)
         << QApplication::translate("MainWindow", "Remove", 0)
        );
        label_104->setText(QApplication::translate("MainWindow", "Bcs eyes color:", 0));
        auraGetEyesColorButton->setText(QApplication::translate("MainWindow", "Get from", 0));
        label_109->setText(QApplication::translate("MainWindow", "More bcs colors:", 0));
        auraAddMoreColorButton->setText(QApplication::translate("MainWindow", "Add from", 0));
        label_110->setText(QApplication::translate("MainWindow", "Bpe Id:", 0));
        auraBpeFlag1Check->setText(QApplication::translate("MainWindow", "Bpe flag 1", 0));
        auraBpeFlag2Check->setText(QApplication::translate("MainWindow", "Bpe flag 2", 0));
        aurBpeButton->setText(QApplication::translate("MainWindow", "Set from", 0));
        label_111->setText(QApplication::translate("MainWindow", "BH64 (detransform):", 0));
        label_112->setText(QApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:700;\">Note: for any bcs colors to work in namekians, make sure to set BH10 to -1.</span></p></body></html>", 0));
        tabWidget->setTabText(tabWidget->indexOf(auraTab), QApplication::translate("MainWindow", "Transformation", 0));
        label_100->setText(QApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">This tab is only for transformation skills for CACS. Ignore it otherwise.</span></p></body></html>", 0));
        label_101->setText(QApplication::translate("MainWindow", "X2M costume:", 0));
        bcsAttachmentSetButton->setText(QApplication::translate("MainWindow", "Set", 0));
        bcsAttachmentRemoveButton->setText(QApplication::translate("MainWindow", "Remove", 0));
        bcsBodyCheck->setText(QApplication::translate("MainWindow", "Enable bcs body", 0));
        bcsBodyRemoveButton->setText(QApplication::translate("MainWindow", "Remove", 0));
        bcsBodyAddButton->setText(QApplication::translate("MainWindow", "Add", 0));
        bcsBodyId->setText(QApplication::translate("MainWindow", "Id to use in BAC:", 0));
        label_105->setText(QApplication::translate("MainWindow", "Race:", 0));
        bcsBodyRaceComboBox->clear();
        bcsBodyRaceComboBox->insertItems(0, QStringList()
         << QApplication::translate("MainWindow", "HUM/SYM", 0)
         << QApplication::translate("MainWindow", "HUF/SYF", 0)
         << QApplication::translate("MainWindow", "NMC", 0)
         << QApplication::translate("MainWindow", "FRI", 0)
         << QApplication::translate("MainWindow", "MAM", 0)
         << QApplication::translate("MainWindow", "MAF", 0)
        );
        tabWidget->setTabText(tabWidget->indexOf(bcsTab), QApplication::translate("MainWindow", "BCS", 0));
        menuFile->setTitle(QApplication::translate("MainWindow", "File", 0));
        menuHelp->setTitle(QApplication::translate("MainWindow", "Help", 0));
        menuTools->setTitle(QApplication::translate("MainWindow", "Tools", 0));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
